#!/usr/bin/env python3
"""finalize.py -- resolve the one genuinely self-referential problem in this
directory, reproducibly.

capture.sh's last record generates the drift report, so at that instant
captured_output.txt's own final record has no `exit=` line yet and the tool
correctly reports transcript-drift against TRANSCRIPT_RECORD_HAS_NO_EXIT.
This script re-runs the identical command once the transcript is complete,
diffs the in-flight report against the final one, and appends a prose NOTE
stating the exact difference and the final report's sha256.

The NOTE is safe to append after the report is generated: it contains no
`=== $ ... ===` header, no `exit=` line, no `Ran N tests` and no verdict, so
it changes nothing the checker reads. This script asserts that by
regenerating the report after the append and requiring byte-equality.

Usage, from the repository root:  sh transcript-drift/capture.sh &&
                                  python3 transcript-drift/finalize.py
"""
import hashlib
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT = os.path.join(HERE, "drift_report_2026-08-04.json")
TRANSCRIPT = os.path.join(HERE, "captured_output.txt")
INVENTORY = os.path.join(HERE, "inventory.json")
CHECKER = os.path.join(HERE, "driftcheck.py")
ROOT = os.path.dirname(HERE)


def run(out_path):
    return subprocess.call([sys.executable, CHECKER, "--root", ROOT,
                            "--inventory", INVENTORY, "-o", out_path])


def keys(report):
    return [(f["tool"], f["code"], json.dumps(f["detail"], sort_keys=True))
            for f in report["findings"]]


def main():
    with open(REPORT, encoding="utf-8") as fh:
        inflight = json.load(fh)
    run(REPORT)
    with open(REPORT, encoding="utf-8") as fh:
        final = json.load(fh)

    only_inflight = [k for k in keys(inflight) if k not in keys(final)]
    only_final = [k for k in keys(final) if k not in keys(inflight)]

    lines = [
        "",
        "NOTE ON SELF-REFERENCE (prose; not a command record)",
        "====================================================",
        "The last record above generated drift_report_2026-08-04.json while",
        "this transcript was still being appended to, so at that instant this",
        "file's final record had no exit= line yet and the tool -- correctly",
        "-- reported transcript-drift against TRANSCRIPT_RECORD_HAS_NO_EXIT.",
        "",
        "The committed report was regenerated by re-running the identical",
        "command once this file was complete. The two were diffed by",
        "finalize.py, which produced these lines. Findings present in only",
        "one of them:",
        "",
    ]
    lines.append("  in-flight only (%d):" % len(only_inflight))
    for tool, code, detail in only_inflight:
        lines.append("    %s  %s" % (tool, code))
        lines.append("      %s" % detail)
    lines.append("  final only (%d):" % len(only_final))
    for tool, code, detail in only_final:
        lines.append("    %s  %s" % (tool, code))
        lines.append("      %s" % detail)
    lines += [
        "",
        "  in-flight: %d findings    committed: %d findings"
        % (len(inflight["findings"]), len(final["findings"])),
        "  stats.transcript-drift identical in both: %s"
        % (inflight["stats"].get("transcript-drift")
           == final["stats"].get("transcript-drift")),
        "",
        "These NOTE lines contain no \"=== $ ... ===\" header, no exit= line,",
        "no \"Ran N tests\" and no verdict, so appending them does not change",
        "what the checker sees. finalize.py verifies that by regenerating the",
        "report after this append and requiring byte-equality; it exits 1 if",
        "the bytes differ.",
        "",
    ]

    with open(TRANSCRIPT, "a", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    with open(REPORT, "rb") as fh:
        before = fh.read()
    run(REPORT + ".recheck")
    with open(REPORT + ".recheck", "rb") as fh:
        after = fh.read()
    os.remove(REPORT + ".recheck")
    digest = hashlib.sha256(before).hexdigest()

    if before != after:
        sys.stderr.write("APPEND CHANGED THE REPORT -- the NOTE is not inert\n")
        return 1

    with open(TRANSCRIPT, "a", encoding="utf-8", newline="\n") as fh:
        fh.write("  Regenerated after the append: byte-identical.\n"
                 "  sha256(drift_report_2026-08-04.json) =\n"
                 "  %s\n" % digest)
    sys.stdout.write("finalized: %d findings, sha256 %s\n"
                     % (len(final["findings"]), digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
