#!/usr/bin/env bash
# Regenerates captured_output.txt. Every record is a real run.
#
# rec() follows this repository's transcript convention with the pipefail
# fix: header line, the real run under `bash -c 'set -o pipefail; ...'`,
# then the real exit status. /bin/sh here is dash, which has no
# `set -o pipefail`, so bash is required and this script says so.
#
# WHY THE SCRATCH DIRECTORY IS ./capture_work AND NOT mktemp -d.
# An earlier version used `mktemp -d` and recorded commands like
#   python3 /tmp/whatever/shebang-mode/shebangmode.py --root /tmp/xyz_AbC3/repo
# which put two machine-specific absolute paths into every header. That
# makes the transcript unreproducible on any other checkout, and
# regen-preflight would report it as permanent drift rather than a masked
# volatile field. A fixed relative directory keeps every recorded command
# relative, so the transcript is identical wherever the repository is
# cloned. It is created and removed by this script, by the same path.
set -u

if ! command -v bash >/dev/null 2>&1; then
    echo "capture.sh: bash is required (for 'set -o pipefail')" >&2
    exit 2
fi
if ! command -v git >/dev/null 2>&1; then
    echo "capture.sh: git is required (the subject of this tool)" >&2
    exit 2
fi

cd "$(dirname "$0")" || exit 2
OUT=captured_output.txt
WORK=capture_work                       # relative, created + removed here

rm -rf "$WORK"                          # a leftover from an aborted run
mkdir -p "$WORK"

rec() {
    printf '\n=== $ %s ===\n' "$*" >> "$OUT"
    bash -c "set -o pipefail; $*" >> "$OUT" 2>&1
    printf 'exit=%s\n' "$?" >> "$OUT"
}

cat > "$OUT" <<'HDR'
############################################################
# captured_output.txt -- regenerated by capture.sh.
# Every record is a real run: header, real output, real exit.
#
# Subject: shebangmode.py, which checks that a Git-tracked text file is
# marked executable in the index IF AND ONLY IF it starts with a shebang.
#
# Every recorded command is relative to this directory, so the transcript
# reproduces wherever the repository is cloned.
############################################################

--- unit suite ---
HDR

rec "python3 -m unittest test_shebangmode"

cat >> "$OUT" <<'NOTE1'

--- a repository that SATISFIES the rule ---
Built by fixture_repo.sh. tool.py is executable and shebanged; NOTES.md
and data.csv are neither; blob.bin is executable, has no shebang, and is
BINARY, so it must be skipped rather than reported. The index modes are
printed first, so the 100755 entries are visible rather than asserted.
NOTE1

rec "bash fixture_repo.sh clean capture_work/repo"
rec "cd capture_work/repo && python3 ../../shebangmode.py --root ."

cat >> "$OUT" <<'NOTE2'

--- the same repository, deliberately broken in BOTH directions ---
deploy.sh is shebanged and left non-executable (SM002). runme is marked
executable and is not a script (SM001). The run must NAME both files
and leave a nonzero status.

(That sentence is worded to avoid starting a line with the word "exit":
transcript-schema reads a line beginning "exit" as an exit record, and an
earlier wrapping of this note added a spurious EXIT_MALFORMED finding to
its repo-wide report.)
NOTE2

rec "bash fixture_repo.sh break capture_work/repo"
rec "cd capture_work/repo && python3 ../../shebangmode.py --root ."

cat >> "$OUT" <<'NOTE3'

--- the fix commands the report prints are real commands ---
Each finding carries a `fix` field. Running both of them and re-scanning
must return the fixture to clean, exit 0. That is what makes the report
actionable rather than merely descriptive.
NOTE3

rec "cd capture_work/repo && git update-index --chmod=+x -- deploy.sh && git update-index --chmod=-x -- runme && git ls-files -s"
rec "cd capture_work/repo && python3 ../../shebangmode.py --root ."

cat >> "$OUT" <<'NOTE4'

--- exclusions ---
An exclusion prefix must skip a whole directory, must NOT match a partial
directory name, and must still list what it skipped.
NOTE4

rec "cd capture_work/repo && mkdir -p generated && printf '#!/usr/bin/env python3\\n' > generated/gen.py && git add -- generated/gen.py && python3 ../../shebangmode.py --root . --quiet -o r.json; python3 -c \"import json;d=json.load(open('r.json'));print('findings',[f['path'] for f in d['findings']])\""
rec "cd capture_work/repo && python3 ../../shebangmode.py --root . --exclude generated --quiet -o r2.json; python3 -c \"import json;d=json.load(open('r2.json'));print('findings',[f['path'] for f in d['findings']]);print('skipped',[(s['path'],s['reason'],s.get('prefix')) for s in d['skipped']])\""
rec "cd capture_work/repo && python3 ../../shebangmode.py --root . --exclude gen --quiet -o r3.json; python3 -c \"import json;d=json.load(open('r3.json'));print('does prefix gen exclude generated/ ?',[s['path'] for s in d['skipped'] if s['reason']=='excluded'])\""

cat >> "$OUT" <<'NOTE5'

--- CLI contract ---
Setup errors are exit 2 and say why on stderr. They must never be
confused with exit 1, which means "mismatches found".
NOTE5

rec "python3 shebangmode.py --root /no/such/dir/zzz"
rec "python3 shebangmode.py --root /"
rec "mkdir -p capture_work/repo/sub && python3 shebangmode.py --root capture_work/repo/sub"

cat >> "$OUT" <<'NOTE5B'

The last record is the one that found a real defect in this tool. git -C
DIR ls-files walks UP to the enclosing repository, so a directory nested
inside a checkout does not make git fail -- it returns the tracked files
at or below DIR, which for a fresh subdirectory is none. The first
version of shebangmode.py printed "status":"ok" and exited 0 for exactly
that input: a silent pass on a repository it had not looked at. --root
must now be the top of a checkout. The unit tests missed it because they
used a directory OUTSIDE any repository, where git really does fail.

The subdirectory used above is inside the FIXTURE repository this script
built, not inside the surrounding checkout. An earlier version put the
scratch directory in the surrounding tree, which made this record say
"is not its root" here and "not inside a Git checkout" when
regen-preflight re-ran it in its .git-stripped copy -- a transcript that
could not reproduce. `--root /` covers the no-repository-at-all case with
a path that means the same thing on every machine.
NOTE5B
rec "cd capture_work/repo && python3 ../../shebangmode.py --root . -o /no/such/dir/zzz/out.json"

cat >> "$OUT" <<'NOTE6'

--- determinism: two runs, byte-identical JSON ---
NOTE6

rec "cd capture_work/repo && python3 ../../shebangmode.py --root . --quiet -o d1.json; python3 ../../shebangmode.py --root . --quiet -o d2.json; cmp d1.json d2.json && echo BYTE_IDENTICAL_two_runs"

printf '\n############################################################\n# END OF TRANSCRIPT\n############################################################\n' >> "$OUT"

rm -rf __pycache__          # created by this script's own runs
rm -rf "$WORK"              # created at the top of this script
echo "capture.sh: wrote $OUT"
