#!/usr/bin/env bash
# Regenerates selfscan_output.txt: this tool run against THIS repository.
#
# WHY THIS IS A SECOND SCRIPT AND NOT PART OF capture.sh.
#
# regen-preflight re-runs every <tool>/capture.sh inside a throwaway copy
# of the repository made with `shutil.copytree(..., ignore=(".git", ...))`
# -- deliberately, so a regeneration cannot touch the real working tree.
# That copy has no .git directory, so `git ls-files` fails there and this
# tool correctly exits 2. A capture.sh containing a self-scan record could
# therefore NEVER reproduce under regen-preflight: it would be reported as
# permanent drift, forever, for a reason that has nothing to do with the
# repository being wrong.
#
# So capture.sh keeps only what reproduces anywhere (fixtures built from
# scratch, CLI contract, determinism), and the repository result lives
# here. regen-preflight discovers regenerators by the exact name
# capture.sh, and transcript-drift and transcript-schema read
# <tool>/captured_output.txt by that exact name, so this second transcript
# is additive and changes nothing either of them sees. Both were checked
# by running them before and after, not assumed.
#
# The cost, stated as a cost: this transcript is scanned by no repo-wide
# tool, so nothing checks that it stays current. Its numbers are also
# quoted in README.md, where they are visible to a reader who can re-run
# one command.
set -u

if ! command -v bash >/dev/null 2>&1; then
    echo "selfscan.sh: bash is required (for 'set -o pipefail')" >&2
    exit 2
fi

cd "$(dirname "$0")" || exit 2
OUT=selfscan_output.txt
WORK=selfscan_work                    # relative, created + removed here

rm -rf "$WORK"
mkdir -p "$WORK"

rec() {
    printf '\n=== $ %s ===\n' "$*" >> "$OUT"
    bash -c "set -o pipefail; $*" >> "$OUT" 2>&1
    printf 'exit=%s\n' "$?" >> "$OUT"
}

cat > "$OUT" <<'HDR'
############################################################
# selfscan_output.txt -- regenerated by selfscan.sh.
# Every record is a real run: header, real output, real exit.
#
# Subject: shebangmode.py run against THIS repository, reported honestly
# rather than made to look clean. Every tracked file here is mode 100644
# while many carry a shebang, so the second half of the rule fails and the
# run exits 1. The counts are NOT restated in this header: an earlier
# version wrote them into the heredoc by hand and they went stale against
# the run printed eleven lines below. Read them from the run.
# See README.md, "Why this repository does not pass", for why they are
# not repaired in this commit.
#
# The counts are taken with this directory already in the index, so they
# are what a reader reproduces AFTER the commit, not before it.
############################################################
HDR

rec "cd .. && python3 shebang-mode/shebangmode.py --root . --quiet -o shebang-mode/selfscan_work/self.json; python3 -c \"import json;d=json.load(open('shebang-mode/selfscan_work/self.json'));print('status',d['status']);print('counts',json.dumps(d['counts'],sort_keys=True));print('by_code',json.dumps(d['findings_by_code'],sort_keys=True));print('first five findings:');[print('   ',f['path'],'|',f['first_line']) for f in d['findings'][:5]]\""
rec "cd .. && git ls-files -s | awk '{print \$1}' | sort | uniq -c"
rec "cd .. && git ls-files -z | xargs -0 -I{} sh -c 'head -c2 \"{}\" | grep -q \"^#!\" && head -1 \"{}\"' 2>/dev/null | sort | uniq -c | sort -rn"

cat >> "$OUT" <<'NOTE1'

--- the first half of the rule has zero violations ---
Not because the repository satisfies it, but because there is nothing
executable to violate it. Reported so the 0 is not read as a pass.
NOTE1

rec "cd .. && python3 -c \"import json;d=json.load(open('shebang-mode/selfscan_work/self.json'));print('SM001 count:', d['findings_by_code'].get('SM001_EXEC_WITHOUT_SHEBANG', 0));print('files tracked executable:', d['counts']['executable'])\""

printf '\n############################################################\n# END OF TRANSCRIPT\n############################################################\n' >> "$OUT"

rm -rf __pycache__
rm -rf "$WORK"                        # created at the top of this script
echo "selfscan.sh: wrote $OUT"
