#!/usr/bin/env python3
"""test_crosscheck.py -- tests for crosscheck.py.

Standard library only (unittest). Run with:

    python3 -m unittest test_crosscheck -v

Fixtures live under fixtures/, generated by make_fixtures.py (see that
file's docstring for why fixture bytes are embedded as base64 rather than
committed as loose files). A handful of tests also read directly from the
copy of this repository claim-crosscheck ships inside (../env-leak-scanner)
to pin the specific, confirmed contradiction the task brief names -- those
tests are grouped in RealRepoContradictionTests and are the only tests in
this file that reach outside claim-crosscheck/.
"""

import io
import json
import os
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stdout, redirect_stderr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import crosscheck as cc  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")
REPO_ROOT = os.path.dirname(HERE)


def fx(*parts):
    return os.path.join(FIXTURES, *parts)


def require_full_repo(testcase):
    """Skip a test that needs sibling tool directories (env-leak-scanner
    etc.) alongside claim-crosscheck -- true when running inside the full
    repository checkout, false for a standalone copy of just this
    directory (e.g. the clean tree shipped separately from the repo)."""
    if not os.path.isdir(os.path.join(REPO_ROOT, "env-leak-scanner")):
        testcase.skipTest(
            "requires the full repository checkout (env-leak-scanner not "
            "found next to claim-crosscheck); this is expected when "
            "running a standalone copy of just this tool directory")


def run_cli(argv):
    """Invoke crosscheck.main() in-process, capturing stdout/stderr."""
    out, err = io.StringIO(), io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        rc = cc.main(argv)
    return rc, out.getvalue(), err.getvalue()


# ---------------------------------------------------------------------
# Canonical JSON
# ---------------------------------------------------------------------

class CanonicalJsonTests(unittest.TestCase):
    def test_sorts_keys(self):
        text = cc.canonical_json({"b": 1, "a": 2})
        self.assertEqual(text, '{"a":2,"b":1}\n')

    def test_compact_separators(self):
        text = cc.canonical_json({"a": [1, 2], "b": {"c": 3}})
        self.assertNotIn(", ", text)
        self.assertNotIn(": ", text)

    def test_trailing_newline(self):
        self.assertTrue(cc.canonical_json({}).endswith("\n"))
        self.assertEqual(cc.canonical_json({}).count("\n"), 1)

    def test_ensure_ascii_escapes_unicode(self):
        text = cc.canonical_json({"x": "café"})
        self.assertIn("\\u00e9", text)
        self.assertNotIn("é", text)

    def test_key_order_independent_of_insertion_order(self):
        d1 = {}
        d1["z"] = 1
        d1["a"] = 2
        d2 = {}
        d2["a"] = 2
        d2["z"] = 1
        self.assertEqual(cc.canonical_json(d1), cc.canonical_json(d2))

    def test_nested_list_of_dicts_sorted(self):
        text = cc.canonical_json({"items": [{"b": 1, "a": 2}]})
        self.assertEqual(text, '{"items":[{"a":2,"b":1}]}\n')


# ---------------------------------------------------------------------
# read_text_exact / load_report
# ---------------------------------------------------------------------

class ReadTextExactTests(unittest.TestCase):
    def test_preserves_crlf(self):
        text = cc.read_text_exact(fx("crlf_tool", "README.md"))
        self.assertIn("\r\n", text)

    def test_reads_utf8_content(self):
        text = cc.read_text_exact(fx("unicode_tool", "README.md"))
        self.assertIn("☃", text)  # snowman

    def test_missing_file_raises_oserror(self):
        with self.assertRaises(OSError):
            cc.read_text_exact(fx("does_not_exist", "README.md"))

    def test_empty_file_reads_as_empty_string(self):
        text = cc.read_text_exact(fx("empty_readme_tool", "README.md"))
        self.assertEqual(text, "")


class LoadReportTests(unittest.TestCase):
    def test_missing_report_raises_report_error(self):
        with self.assertRaises(cc.ReportError):
            cc.load_report(fx("missing_report_tool", "nonexistent.json"))

    def test_invalid_json_raises_report_error(self):
        with self.assertRaises(cc.ReportError):
            cc.load_report(fx("invalid_json_tool", "report.json"))

    def test_non_object_top_level_raises_report_error(self):
        with self.assertRaises(cc.ReportError):
            cc.load_report(fx("not_object_tool", "report.json"))

    def test_valid_report_loads_as_dict(self):
        report = cc.load_report(fx("match_tool", "report.json"))
        self.assertIsInstance(report, dict)
        self.assertIn("confirmed_leaks", report)

    def test_non_utf8_bytes_raise_report_error(self):
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "bad.json")
            with open(p, "wb") as fh:
                fh.write(b"\xff\xfe{}")
            with self.assertRaises(cc.ReportError):
                cc.load_report(p)

    def test_error_message_includes_path(self):
        try:
            cc.load_report(fx("invalid_json_tool", "report.json"))
            self.fail("expected ReportError")
        except cc.ReportError as exc:
            self.assertIn("report.json", str(exc))


# ---------------------------------------------------------------------
# RFC 6901 JSON Pointer helpers
# ---------------------------------------------------------------------

class JsonPointerTests(unittest.TestCase):
    def test_empty_parts_is_root_pointer(self):
        self.assertEqual(cc.make_pointer([]), "")

    def test_simple_pointer(self):
        self.assertEqual(cc.make_pointer(["confirmed_leaks", 3]), "/confirmed_leaks/3")

    def test_escapes_tilde(self):
        self.assertEqual(cc.pointer_escape("a~b"), "a~0b")

    def test_escapes_slash(self):
        self.assertEqual(cc.pointer_escape("a/b"), "a~1b")

    def test_escapes_both_in_pointer(self):
        pointer = cc.make_pointer(["weird~key/name", 0])
        self.assertEqual(pointer, "/weird~0key~1name/0")

    def test_integer_index_not_escaped(self):
        pointer = cc.make_pointer(["bucket", 12])
        self.assertTrue(pointer.endswith("/12"))

    def test_resolve_pointer_root(self):
        data = {"a": 1}
        self.assertIs(cc.resolve_pointer(data, ""), data)

    def test_resolve_pointer_nested(self):
        data = {"a": [{"b": 5}]}
        self.assertEqual(cc.resolve_pointer(data, "/a/0/b"), 5)

    def test_resolve_pointer_roundtrip_with_escaping(self):
        data = {"weird~key/name": [1, 2, 3]}
        pointer = cc.make_pointer(["weird~key/name", 2])
        self.assertEqual(cc.resolve_pointer(data, pointer), 3)

    def test_resolve_pointer_missing_key_raises(self):
        with self.assertRaises(KeyError):
            cc.resolve_pointer({"a": 1}, "/b")

    def test_resolve_pointer_invalid_no_leading_slash(self):
        with self.assertRaises(ValueError):
            cc.resolve_pointer({"a": 1}, "a")


class IterTreeTests(unittest.TestCase):
    def test_yields_root_first(self):
        data = {"a": 1}
        first = next(cc.iter_tree(data))
        self.assertEqual(first, ([], data))

    def test_dict_keys_sorted(self):
        data = {"z": 1, "a": 2}
        parts_seen = [p for p, _ in cc.iter_tree(data)]
        self.assertEqual(parts_seen, [[], ["a"], ["z"]])

    def test_list_indices_in_order(self):
        data = [10, 20, 30]
        parts_seen = [p for p, v in cc.iter_tree(data) if p]
        self.assertEqual(parts_seen, [[0], [1], [2]])

    def test_deterministic_across_dict_construction_order(self):
        d1, d2 = {}, {}
        d1["b"] = 1
        d1["a"] = 2
        d2["a"] = 2
        d2["b"] = 1
        self.assertEqual(list(cc.iter_tree(d1)), list(cc.iter_tree(d2)))


# ---------------------------------------------------------------------
# Bucket classification / file lookup
# ---------------------------------------------------------------------

class ClassifyBucketsTests(unittest.TestCase):
    def test_confirmed_leaks_is_positive(self):
        polarity = cc.classify_buckets({"confirmed_leaks": []})
        self.assertEqual(polarity["confirmed_leaks"], "positive")

    def test_reviewed_benign_is_negative(self):
        polarity = cc.classify_buckets({"reviewed_benign": []})
        self.assertEqual(polarity["reviewed_benign"], "negative")

    def test_stale_review_entries_is_negative(self):
        polarity = cc.classify_buckets({"stale_review_entries": []})
        self.assertEqual(polarity["stale_review_entries"], "negative")

    def test_non_list_values_are_not_classified(self):
        polarity = cc.classify_buckets({"schema_version": 1, "tool": "x"})
        self.assertEqual(polarity, {})

    def test_each_negative_keyword_detected(self):
        for kw in ("benign", "stale", "ignored", "exempt", "excluded",
                   "suppressed", "dismissed", "skipped", "allowlist",
                   "allowed", "denylist"):
            report = {"some_%s_bucket" % kw: []}
            polarity = cc.classify_buckets(report)
            self.assertEqual(polarity["some_%s_bucket" % kw], "negative",
                              "keyword %r should be negative" % kw)

    def test_unrelated_name_is_positive(self):
        polarity = cc.classify_buckets({"findings": []})
        self.assertEqual(polarity["findings"], "positive")


class EntryFileValueTests(unittest.TestCase):
    def test_file_key(self):
        self.assertEqual(cc.entry_file_value({"file": "a.py"}), "a.py")

    def test_path_key(self):
        self.assertEqual(cc.entry_file_value({"path": "a.py"}), "a.py")

    def test_filename_key(self):
        self.assertEqual(cc.entry_file_value({"filename": "a.py"}), "a.py")

    def test_file_key_takes_priority_over_path(self):
        entry = {"file": "a.py", "path": "b.py"}
        self.assertEqual(cc.entry_file_value(entry), "a.py")

    def test_non_dict_returns_none(self):
        self.assertIsNone(cc.entry_file_value("not a dict"))
        self.assertIsNone(cc.entry_file_value(None))
        self.assertIsNone(cc.entry_file_value(42))

    def test_no_file_key_returns_none(self):
        self.assertIsNone(cc.entry_file_value({"tool": "x"}))

    def test_non_string_file_value_returns_none(self):
        self.assertIsNone(cc.entry_file_value({"file": 123}))


class EntryCategoryValueTests(unittest.TestCase):
    def test_category_key(self):
        self.assertEqual(cc.entry_category_value({"category": "hostname"}),
                          "hostname")

    def test_type_key_fallback(self):
        self.assertEqual(cc.entry_category_value({"type": "hostname"}),
                          "hostname")

    def test_missing_returns_none(self):
        self.assertIsNone(cc.entry_category_value({}))


class TokenPrefixTests(unittest.TestCase):
    def test_trailing_slash_is_prefix(self):
        self.assertTrue(cc.is_prefix_token("doc-validator/"))

    def test_bare_directory_name_is_prefix(self):
        self.assertTrue(cc.is_prefix_token("doc-validator"))

    def test_filename_with_extension_is_not_prefix(self):
        self.assertFalse(cc.is_prefix_token("LIMITATIONS.md"))

    def test_nested_file_with_extension_is_not_prefix(self):
        self.assertFalse(cc.is_prefix_token("snapshot-diff/README.md"))

    def test_dotted_directory_name_last_segment_no_dot(self):
        self.assertTrue(cc.is_prefix_token("a.b/c"))

    def test_file_matches_token_exact(self):
        self.assertTrue(cc.file_matches_token("LIMITATIONS.md", "LIMITATIONS.md"))
        self.assertFalse(cc.file_matches_token("LIMITATIONS.md", "OTHER.md"))

    def test_file_matches_token_prefix_with_slash(self):
        self.assertTrue(cc.file_matches_token("doc-validator/x.txt",
                                                "doc-validator/"))

    def test_file_matches_token_prefix_without_slash(self):
        self.assertTrue(cc.file_matches_token("doc-validator/x.txt",
                                                "doc-validator"))

    def test_file_matches_token_prefix_does_not_match_sibling(self):
        self.assertFalse(cc.file_matches_token("doc-validator-extra/x.txt",
                                                 "doc-validator"))

    def test_file_matches_token_prefix_matches_directory_itself(self):
        self.assertTrue(cc.file_matches_token("doc-validator", "doc-validator/"))


# ---------------------------------------------------------------------
# find_file_matches / summaries
# ---------------------------------------------------------------------

class FindFileMatchesTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [
                {"file": "a.py", "line": 1, "category": "hostname"},
            ],
            "reviewed_benign": [
                {"file": "b.py", "line": 2, "category": "hostname"},
            ],
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_finds_positive_match(self):
        matches = cc.find_file_matches(self.report, self.polarity, "a.py")
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].polarity, "positive")

    def test_finds_negative_match(self):
        matches = cc.find_file_matches(self.report, self.polarity, "b.py")
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].polarity, "negative")

    def test_no_match_returns_empty(self):
        matches = cc.find_file_matches(self.report, self.polarity, "c.py")
        self.assertEqual(matches, [])

    def test_pointer_parts_correct(self):
        matches = cc.find_file_matches(self.report, self.polarity, "a.py")
        self.assertEqual(matches[0].pointer_parts, ["confirmed_leaks", 0])

    def test_deterministic_bucket_order(self):
        # buckets iterated alphabetically regardless of dict insertion order
        report2 = {}
        report2["reviewed_benign"] = self.report["reviewed_benign"]
        report2["confirmed_leaks"] = self.report["confirmed_leaks"]
        polarity2 = cc.classify_buckets(report2)
        matches1 = cc.find_file_matches(self.report, self.polarity, "a.py")
        matches2 = cc.find_file_matches(report2, polarity2, "a.py")
        self.assertEqual(matches1[0].pointer_parts, matches2[0].pointer_parts)


class SummaryAndDistinctFilesTests(unittest.TestCase):
    def test_whole_report_bucket_summary(self):
        report = {"confirmed_leaks": [1, 2], "reviewed_benign": [1]}
        polarity = cc.classify_buckets(report)
        summary = cc.whole_report_bucket_summary(report, polarity)
        self.assertEqual(summary, {"confirmed_leaks": 2, "reviewed_benign": 1})

    def test_distinct_positive_files_excludes_negative(self):
        report = {
            "confirmed_leaks": [{"file": "a.py"}, {"file": "b.py"}],
            "reviewed_benign": [{"file": "c.py"}],
        }
        polarity = cc.classify_buckets(report)
        files = cc.distinct_positive_files(report, polarity)
        self.assertEqual(files, ["a.py", "b.py"])

    def test_distinct_positive_files_deduplicates(self):
        report = {"confirmed_leaks": [{"file": "a.py"}, {"file": "a.py"}]}
        polarity = cc.classify_buckets(report)
        self.assertEqual(cc.distinct_positive_files(report, polarity), ["a.py"])

    def test_excerpt_for_entry_is_canonical(self):
        excerpt = cc.excerpt_for_entry({"b": 1, "a": 2})
        self.assertEqual(excerpt, '{"a":2,"b":1}')
        self.assertNotIn("\n", excerpt)


# ---------------------------------------------------------------------
# looks_like_path_token
# ---------------------------------------------------------------------

class LooksLikePathTokenTests(unittest.TestCase):
    def test_file_with_extension_is_path(self):
        self.assertTrue(cc.looks_like_path_token("LIMITATIONS.md"))

    def test_nested_file_is_path(self):
        self.assertTrue(cc.looks_like_path_token("snapshot-diff/README.md"))

    def test_directory_with_trailing_slash_is_path(self):
        self.assertTrue(cc.looks_like_path_token("doc-validator/"))

    def test_bare_word_is_not_path(self):
        self.assertFalse(cc.looks_like_path_token("weak-assertion-scanner"))

    def test_bare_word_with_dashes_only_not_path(self):
        self.assertFalse(cc.looks_like_path_token("python3"))

    def test_token_with_spaces_rejected(self):
        self.assertFalse(cc.looks_like_path_token("not a path"))

    def test_token_with_special_chars_rejected(self):
        self.assertFalse(cc.looks_like_path_token("foo(bar).md"))

    def test_root_relative_double_slash(self):
        self.assertTrue(cc.looks_like_path_token("a/b/c.txt"))

    def test_extension_too_long_rejected_as_extension_but_slash_ok(self):
        # no slash, and the "extension" is too long to count -> not a path
        self.assertFalse(cc.looks_like_path_token("a.reallylongext"))


# ---------------------------------------------------------------------
# sentence_spans / line_of
# ---------------------------------------------------------------------

class SentenceSpansTests(unittest.TestCase):
    def test_line_of_first_line(self):
        self.assertEqual(cc.line_of("abc\ndef", 0), 1)

    def test_line_of_second_line(self):
        self.assertEqual(cc.line_of("abc\ndef", 4), 2)

    def test_line_of_at_newline(self):
        self.assertEqual(cc.line_of("abc\ndef", 3), 1)

    def test_spans_cover_whole_text(self):
        text = "One. Two. Three."
        spans = cc.sentence_spans(text)
        self.assertEqual(spans[0][0], 0)
        self.assertEqual(spans[-1][1], len(text))

    def test_spans_split_on_capital_after_period(self):
        text = "First sentence. Second sentence."
        spans = cc.sentence_spans(text)
        pieces = [text[a:b] for a, b in spans]
        self.assertEqual(len(pieces), 2)
        self.assertTrue(pieces[1].startswith("Second"))

    def test_spans_split_on_blank_line(self):
        text = "Paragraph one.\n\nParagraph two."
        spans = cc.sentence_spans(text)
        self.assertGreaterEqual(len(spans), 2)

    def test_span_containing_finds_correct_span(self):
        text = "First. Second."
        spans = cc.sentence_spans(text)
        a, b = cc.span_containing(spans, 8)
        self.assertIn("Second", text[a:b])

    def test_span_containing_out_of_range_falls_back(self):
        spans = [(0, 5)]
        self.assertEqual(cc.span_containing(spans, 100), (0, 5))

    def test_empty_text_spans(self):
        self.assertEqual(cc.sentence_spans(""), [])


# ---------------------------------------------------------------------
# Fenced code block masking
# ---------------------------------------------------------------------

class MaskFencedBlocksTests(unittest.TestCase):
    def test_preserves_length(self):
        text = "before\n```\ncode 999 confirmed\n```\nafter"
        masked = cc.mask_fenced_blocks(text)
        self.assertEqual(len(masked), len(text))

    def test_preserves_newlines(self):
        text = "a\n```\nb\nc\n```\nd"
        masked = cc.mask_fenced_blocks(text)
        self.assertEqual(masked.count("\n"), text.count("\n"))

    def test_blanks_fence_interior(self):
        text = "```\n999 confirmed leaks\n```"
        masked = cc.mask_fenced_blocks(text)
        self.assertNotIn("999", masked)

    def test_leaves_outside_content_untouched(self):
        text = "121 confirmed leaks\n```\n999 confirmed leaks\n```"
        masked = cc.mask_fenced_blocks(text)
        self.assertTrue(masked.startswith("121 confirmed leaks\n"))

    def test_no_fence_unchanged(self):
        text = "no fences here at all"
        self.assertEqual(cc.mask_fenced_blocks(text), text)

    def test_unterminated_fence_left_unmasked(self):
        text = "before\n```\nunterminated 999 confirmed"
        masked = cc.mask_fenced_blocks(text)
        self.assertIn("999", masked)

    def test_multiple_fences_both_masked(self):
        text = "```\n1 confirmed\n```\ntext\n```\n2 confirmed\n```"
        masked = cc.mask_fenced_blocks(text)
        self.assertNotIn("1 confirmed", masked)
        self.assertNotIn("2 confirmed", masked)
        self.assertIn("text", masked)


# ---------------------------------------------------------------------
# extract_table_count_claims
# ---------------------------------------------------------------------

class ExtractTableCountTests(unittest.TestCase):
    def test_extracts_row_under_category_header(self):
        text = "| Category | Confirmed |\n|---|---|\n| `hostname` | 20 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["category"], "hostname")
        self.assertEqual(claims[0].extra["expected"], 20)

    def test_ignores_row_without_category_header(self):
        text = ("| After planting | `confirmed` | `by_category` delta |\n"
                 "|---|---|---|\n"
                 "| `/opt/build/out.json` | 1 |\n")
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_multiple_rows_extracted(self):
        text = ("| Category | Confirmed |\n|---|---|\n"
                 "| `a` | 1 |\n| `b` | 2 |\n")
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(len(claims), 2)

    def test_ignores_three_column_rules_table(self):
        text = ("| Category | Rules | Example |\n|---|---|---|\n"
                 "| `hostname` | EL-HOST | x |\n")
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_zero_count_extracted(self):
        text = "| Category | Confirmed |\n|---|---|\n| `username` | 0 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(claims[0].extra["expected"], 0)

    def test_readme_line_correct(self):
        text = "preamble\n\n| Category | Confirmed |\n|---|---|\n| `x` | 3 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(claims[0].readme_line, 5)

    def test_quote_is_exact_row_substring(self):
        text = "| Category | Confirmed |\n|---|---|\n| `x` | 3 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        start = text.index("| `x`")
        self.assertEqual(claims[0].readme_quote, "| `x` | 3 |")
        self.assertEqual(text[start:start + len(claims[0].readme_quote)],
                          claims[0].readme_quote)

    def test_case_insensitive_category_header_word(self):
        text = "| CATEGORY | Confirmed |\n|---|---|\n| `x` | 3 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)

    def test_header_word_inside_compound_not_matched(self):
        # "by_category" contains "category" as a substring but not as a
        # separate word -- must NOT count as a header match.
        text = "| planting | `by_category` delta |\n|---|---|\n| `x` | 3 |\n"
        claims = cc.extract_table_count_claims(text, "R.md")
        self.assertEqual(claims, [])


# ---------------------------------------------------------------------
# extract_summary_count_claims
# ---------------------------------------------------------------------

class ExtractSummaryCountTests(unittest.TestCase):
    def test_confirmed_leaks_singular_and_plural(self):
        for phrase, n in [("1 confirmed leak", 1), ("121 confirmed leaks", 121)]:
            claims = cc.extract_summary_count_claims(phrase, "R.md")
            confirmed = [c for c in claims if c.extra.get("metric") == "confirmed"]
            self.assertEqual(len(confirmed), 1, phrase)
            self.assertEqual(confirmed[0].extra["expected"], n, phrase)

    def test_benign_phrase(self):
        text = "100 matches reviewed and dismissed as benign"
        claims = cc.extract_summary_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["metric"], "benign")
        self.assertEqual(claims[0].extra["expected"], 100)

    def test_stale_phrase(self):
        text = "0 stale review entries"
        claims = cc.extract_summary_count_claims(text, "R.md")
        metrics = {c.extra["metric"]: c.extra["expected"] for c in claims}
        self.assertEqual(metrics.get("stale"), 0)

    def test_stale_singular(self):
        text = "1 stale review entry"
        claims = cc.extract_summary_count_claims(text, "R.md")
        self.assertTrue(any(c.extra["metric"] == "stale" for c in claims))

    def test_across_files_phrase(self):
        text = "across 23 files"
        claims = cc.extract_summary_count_claims(text, "R.md")
        distinct = [c for c in claims if c.kind == "DISTINCT_FILE_COUNT"]
        self.assertEqual(len(distinct), 1)
        self.assertEqual(distinct[0].extra["expected"], 23)

    def test_across_one_file_singular(self):
        text = "across 1 file"
        claims = cc.extract_summary_count_claims(text, "R.md")
        self.assertEqual(claims[0].extra["expected"], 1)

    def test_combined_summary_sentence_yields_all_three(self):
        text = ("121 confirmed leaks across 23 files, 100 matches reviewed "
                 "and dismissed as benign, 0 stale review entries.")
        claims = cc.extract_summary_count_claims(text, "R.md")
        kinds = sorted((c.kind, c.extra.get("metric")) for c in claims)
        self.assertIn(("DISTINCT_FILE_COUNT", None), kinds)
        self.assertIn(("SUMMARY_COUNT", "confirmed"), kinds)
        self.assertIn(("SUMMARY_COUNT", "benign"), kinds)
        self.assertIn(("SUMMARY_COUNT", "stale"), kinds)

    def test_no_match_no_claims(self):
        self.assertEqual(cc.extract_summary_count_claims("nothing here", "R.md"), [])

    def test_case_insensitive_confirmed(self):
        text = "5 CONFIRMED LEAKS"
        claims = cc.extract_summary_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)


# ---------------------------------------------------------------------
# extract_presence_claims
# ---------------------------------------------------------------------

class ExtractPresenceTests(unittest.TestCase):
    def test_single_token_carries(self):
        text = "`a.py` carries a leak."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual([c.extra["token"] for c in claims], ["a.py"])

    def test_comma_and_and_list_all_included(self):
        text = "`a.py`, `b.py`, `c.py` and `d.py` carry the rest."
        claims = cc.extract_presence_claims(text, "R.md")
        tokens = [c.extra["token"] for c in claims]
        self.assertEqual(tokens, ["a.py", "b.py", "c.py", "d.py"])

    def test_glue_break_excludes_earlier_tokens(self):
        text = "`a.py`, keyed by `b.py`, and every entry carries a `reason`."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_is_flagged_variant(self):
        text = "`x/y.txt` is flagged as a problem."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["token"], "x/y.txt")

    def test_are_flagged_variant(self):
        text = "`x/y.txt` and `x/z.txt` are flagged."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 2)

    def test_is_present_variant(self):
        text = "`x/y.txt` is present in the report."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 1)

    def test_are_present_variant(self):
        text = "`x/y.txt` and `x/z.txt` are present."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 2)

    def test_non_path_tokens_filtered_out_of_chain(self):
        text = "`weak-assertion-scanner` alone carries the finding."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_carrying_gerund_form(self):
        text = "`a.py` is carrying the finding forward."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 1)

    def test_no_backtick_before_verb_yields_nothing(self):
        text = "This sentence carries no backtick token at all."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_quote_is_exact_substring(self):
        text = "Intro text. `a.py` carries a leak. More text."
        claims = cc.extract_presence_claims(text, "R.md")
        c = claims[0]
        idx = text.index(c.readme_quote)
        self.assertEqual(text[idx:idx + len(c.readme_quote)], c.readme_quote)

    def test_readme_line_matches_token_line(self):
        text = "line one\nline two\n`a.py` carries a leak on line three.\n"
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(claims[0].readme_line, 3)

    def test_duplicate_token_same_clause_deduplicated(self):
        text = "`a.py`, `a.py` carry it."
        claims = cc.extract_presence_claims(text, "R.md")
        self.assertEqual(len(claims), 1)

    def test_directory_token_with_trailing_slash(self):
        text = "`doc-validator/` and `bundle-index/` carry the rest."
        claims = cc.extract_presence_claims(text, "R.md")
        tokens = [c.extra["token"] for c in claims]
        self.assertEqual(tokens, ["doc-validator/", "bundle-index/"])

    def test_multiline_clause_glue_across_newline(self):
        text = "`a.py`,\n`b.py` and `c.py` carry\nthe rest."
        claims = cc.extract_presence_claims(text, "R.md")
        tokens = [c.extra["token"] for c in claims]
        self.assertEqual(tokens, ["a.py", "b.py", "c.py"])

    def test_sentence_boundary_stops_backward_walk(self):
        text = "Earlier sentence names `z.py`. Later, `a.py` carries a leak."
        claims = cc.extract_presence_claims(text, "R.md")
        tokens = [c.extra["token"] for c in claims]
        self.assertEqual(tokens, ["a.py"])


# ---------------------------------------------------------------------
# extract_location_claims
# ---------------------------------------------------------------------

class ExtractLocationTests(unittest.TestCase):
    def test_basic_location(self):
        text = "is present, at `weak-assertion-scanner/README.md` line 281:"
        claims = cc.extract_location_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["token"],
                          "weak-assertion-scanner/README.md")
        self.assertEqual(claims[0].extra["claimed_line"], 281)

    def test_non_path_token_rejected(self):
        text = "at `weak-assertion-scanner` line 281"
        claims = cc.extract_location_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_no_match_without_line_number(self):
        text = "at `a.py` somewhere"
        claims = cc.extract_location_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_multiple_locations(self):
        text = "at `a.py` line 1 and separately at `b.py` line 2"
        claims = cc.extract_location_claims(text, "R.md")
        self.assertEqual(len(claims), 2)

    def test_quote_is_exact_match_span(self):
        text = "found at `a.py` line 42 in the report"
        claims = cc.extract_location_claims(text, "R.md")
        self.assertEqual(claims[0].readme_quote, "at `a.py` line 42")


# ---------------------------------------------------------------------
# extract_category_claims
# ---------------------------------------------------------------------

class ExtractCategoryTests(unittest.TestCase):
    def test_basic_category_claim(self):
        text = "`a.py` is a `hostname` leak."
        claims = cc.extract_category_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["token"], "a.py")
        self.assertEqual(claims[0].extra["category"], "hostname")

    def test_an_variant(self):
        text = "`a.py` is an `absolute_path` leak."
        claims = cc.extract_category_claims(text, "R.md")
        self.assertEqual(claims[0].extra["category"], "absolute_path")

    def test_non_path_token_rejected(self):
        text = "`scanner` is a `hostname` leak."
        claims = cc.extract_category_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_no_match_without_leak_word(self):
        text = "`a.py` is a `hostname` finding."
        claims = cc.extract_category_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_case_insensitive_is_a(self):
        text = "`a.py` IS A `hostname` leak."
        claims = cc.extract_category_claims(text, "R.md")
        self.assertEqual(len(claims), 1)


# ---------------------------------------------------------------------
# extract_dir_count_claims
# ---------------------------------------------------------------------

class ExtractDirCountTests(unittest.TestCase):
    def test_alone_accounts_for(self):
        text = "`weak-thing/x.py` alone accounts for 12 of them."
        claims = cc.extract_dir_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["expected"], 12)

    def test_accounts_for_without_alone(self):
        text = "`weak-thing/x.py` accounts for 12 of them."
        claims = cc.extract_dir_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)

    def test_bare_directory_name_rejected(self):
        text = "`weak-assertion-scanner` alone accounts for 12 of them."
        claims = cc.extract_dir_count_claims(text, "R.md")
        self.assertEqual(claims, [])

    def test_directory_with_slash_accepted(self):
        text = "`weak-thing/` alone accounts for 12 of them."
        claims = cc.extract_dir_count_claims(text, "R.md")
        self.assertEqual(len(claims), 1)
        self.assertEqual(claims[0].extra["token"], "weak-thing/")

    def test_no_match_without_of_them(self):
        text = "`weak-thing/x.py` accounts for a lot."
        claims = cc.extract_dir_count_claims(text, "R.md")
        self.assertEqual(claims, [])


# ---------------------------------------------------------------------
# extract_claims (composition)
# ---------------------------------------------------------------------

class ExtractClaimsTests(unittest.TestCase):
    def test_empty_readme_yields_no_claims(self):
        self.assertEqual(cc.extract_claims("R.md", ""), [])

    def test_no_claims_prose_yields_nothing(self):
        text = cc.read_text_exact(fx("no_claims_tool", "README.md"))
        self.assertEqual(cc.extract_claims("R.md", text), [])

    def test_claims_sorted_by_line(self):
        text = "`b.py` carries it.\n`a.py` carries it too on a later line."
        claims = cc.extract_claims("R.md", text)
        lines = [c.readme_line for c in claims]
        self.assertEqual(lines, sorted(lines))

    def test_fenced_block_excluded_from_all_kinds(self):
        text = ("```\n`fenced.py` carries a leak, at `fenced.py` line 1. "
                 "5 confirmed leaks.\n```\n")
        claims = cc.extract_claims("R.md", text)
        self.assertEqual(claims, [])

    def test_match_tool_readme_claim_count(self):
        text = cc.read_text_exact(fx("match_tool", "README.md"))
        claims = cc.extract_claims("R.md", text)
        self.assertEqual(len(claims), 9)


# ---------------------------------------------------------------------
# evaluate_* functions
# ---------------------------------------------------------------------

def _claim(kind, **extra):
    return cc.Claim(kind, "R.md", 1, "quote", **extra)


class EvaluatePresenceTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [{"file": "a.py", "line": 1, "category": "hostname"}],
            "reviewed_benign": [{"file": "b.py", "line": 2, "category": "hostname"}],
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_match_when_in_positive_bucket(self):
        claim = _claim("PRESENCE", token="a.py")
        result = cc.evaluate_presence(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_discrepancy_when_only_negative_bucket(self):
        claim = _claim("PRESENCE", token="b.py")
        result = cc.evaluate_presence(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "/reviewed_benign/0")

    def test_discrepancy_carries_required_fields(self):
        claim = _claim("PRESENCE", token="b.py")
        result = cc.evaluate_presence(claim, self.report, self.polarity, "r.json")
        for field in ("readme_path", "readme_line", "readme_quote",
                      "report_path", "json_pointer", "report_excerpt"):
            self.assertIn(field, result)

    def test_discrepancy_when_absent_everywhere(self):
        claim = _claim("PRESENCE", token="c.py")
        result = cc.evaluate_presence(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "")

    def test_prefix_token_match(self):
        claim = _claim("PRESENCE", token="./")
        report = {"confirmed_leaks": [{"file": "./x.py", "line": 1}]}
        polarity = cc.classify_buckets(report)
        result = cc.evaluate_presence(claim, report, polarity, "r.json")
        self.assertIsNone(result)


class EvaluateLocationTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [{"file": "a.py", "line": 281, "category": "hostname"}],
            "reviewed_benign": [{"file": "b.py", "line": 5}],
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_match_when_line_matches(self):
        claim = _claim("LOCATION", token="a.py", claimed_line=281)
        result = cc.evaluate_location(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_discrepancy_when_line_differs(self):
        claim = _claim("LOCATION", token="a.py", claimed_line=999)
        result = cc.evaluate_location(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)

    def test_discrepancy_when_only_negative_bucket_has_it(self):
        claim = _claim("LOCATION", token="b.py", claimed_line=5)
        result = cc.evaluate_location(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "/reviewed_benign/0")

    def test_discrepancy_when_absent(self):
        claim = _claim("LOCATION", token="z.py", claimed_line=1)
        result = cc.evaluate_location(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "")


class EvaluateCategoryTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [{"file": "a.py", "line": 1, "category": "hostname"}],
            "reviewed_benign": [{"file": "b.py", "line": 2, "category": "hostname"}],
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_match_when_category_equal(self):
        claim = _claim("CATEGORY", token="a.py", category="hostname")
        result = cc.evaluate_category(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_match_is_case_insensitive(self):
        claim = _claim("CATEGORY", token="a.py", category="HOSTNAME")
        result = cc.evaluate_category(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_discrepancy_when_category_differs(self):
        claim = _claim("CATEGORY", token="a.py", category="temp_directory")
        result = cc.evaluate_category(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)

    def test_discrepancy_when_only_negative(self):
        claim = _claim("CATEGORY", token="b.py", category="hostname")
        result = cc.evaluate_category(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "/reviewed_benign/0")

    def test_discrepancy_when_absent(self):
        claim = _claim("CATEGORY", token="z.py", category="hostname")
        result = cc.evaluate_category(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)


class EvaluateDirCountTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [
                {"file": "d/a.py", "line": 1},
                {"file": "d/b.py", "line": 2},
            ],
            "reviewed_benign": [{"file": "d/c.py", "line": 3}],
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_match_correct_count(self):
        claim = _claim("DIR_COUNT", token="d/", expected=2)
        result = cc.evaluate_dir_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_negative_bucket_not_counted(self):
        claim = _claim("DIR_COUNT", token="d/", expected=3)
        result = cc.evaluate_dir_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)

    def test_zero_expected_zero_found(self):
        claim = _claim("DIR_COUNT", token="nowhere/", expected=0)
        result = cc.evaluate_dir_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)


class EvaluateTableCountTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [],
            "counts": {"confirmed": 0, "by_category": {"hostname": 20,
                                                         "temp_directory": 101}},
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_match(self):
        claim = _claim("TABLE_COUNT", category="hostname", expected=20)
        result = cc.evaluate_table_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_mismatch(self):
        claim = _claim("TABLE_COUNT", category="hostname", expected=99)
        result = cc.evaluate_table_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "/counts/by_category/hostname")

    def test_unknown_category_field_missing(self):
        claim = _claim("TABLE_COUNT", category="does_not_exist", expected=1)
        result = cc.evaluate_table_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "")


class EvaluateSummaryCountTests(unittest.TestCase):
    def setUp(self):
        self.report = {
            "confirmed_leaks": [1, 2, 3],
            "reviewed_benign": [1],
            "stale_review_entries": [],
            "counts": {"confirmed": 3, "benign": 1},
        }
        self.polarity = cc.classify_buckets(self.report)

    def test_confirmed_match_via_counts(self):
        claim = _claim("SUMMARY_COUNT", metric="confirmed", expected=3)
        result = cc.evaluate_summary_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_benign_match(self):
        claim = _claim("SUMMARY_COUNT", metric="benign", expected=1)
        result = cc.evaluate_summary_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_stale_match_via_bucket_length(self):
        claim = _claim("SUMMARY_COUNT", metric="stale", expected=0)
        result = cc.evaluate_summary_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNone(result)

    def test_mismatch(self):
        claim = _claim("SUMMARY_COUNT", metric="confirmed", expected=999)
        result = cc.evaluate_summary_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)

    def test_metric_not_found(self):
        claim = _claim("SUMMARY_COUNT", metric="nosuchmetric", expected=1)
        result = cc.evaluate_summary_count(claim, self.report, self.polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "")

    def test_ambiguous_candidates_picks_lexicographically_smallest_pointer(self):
        report = {
            "confirmed_leaks": [1, 2],
            "counts": {"confirmed": 5},
        }
        polarity = cc.classify_buckets(report)
        claim = _claim("SUMMARY_COUNT", metric="confirmed", expected=2)
        result = cc.evaluate_summary_count(claim, report, polarity, "r.json")
        # counts.confirmed=5 != 2, confirmed_leaks len=2 == 2, differing
        # values -> mismatch reported, sorted pointer choice is deterministic
        self.assertIsNotNone(result)
        self.assertEqual(result["json_pointer"], "/confirmed_leaks")


class EvaluateDistinctFileCountTests(unittest.TestCase):
    def test_match(self):
        report = {"confirmed_leaks": [{"file": "a.py"}, {"file": "b.py"}]}
        polarity = cc.classify_buckets(report)
        claim = _claim("DISTINCT_FILE_COUNT", expected=2)
        result = cc.evaluate_distinct_file_count(claim, report, polarity, "r.json")
        self.assertIsNone(result)

    def test_mismatch(self):
        report = {"confirmed_leaks": [{"file": "a.py"}]}
        polarity = cc.classify_buckets(report)
        claim = _claim("DISTINCT_FILE_COUNT", expected=5)
        result = cc.evaluate_distinct_file_count(claim, report, polarity, "r.json")
        self.assertIsNotNone(result)
        self.assertEqual(result["report_excerpt"], '["a.py"]')


class FindIntMetricTests(unittest.TestCase):
    def test_finds_top_level_counts_key(self):
        report = {"counts": {"confirmed": 5}}
        found = cc.find_int_metric(report, "confirmed")
        self.assertIn((["counts", "confirmed"], 5), found)

    def test_finds_nested_by_category(self):
        report = {"counts": {"by_category": {"hostname": 20}}}
        found = cc.find_int_metric(report, "hostname")
        self.assertIn((["counts", "by_category", "hostname"], 20), found)

    def test_finds_bucket_length(self):
        report = {"confirmed_leaks": [1, 2, 3]}
        found = cc.find_int_metric(report, "confirmed")
        self.assertIn((["confirmed_leaks"], 3), found)

    def test_bool_values_excluded(self):
        report = {"counts": {"confirmed_flag": True}}
        found = cc.find_int_metric(report, "confirmed")
        self.assertEqual(found, [])

    def test_no_counts_key_still_checks_buckets(self):
        report = {"stale_review_entries": []}
        found = cc.find_int_metric(report, "stale")
        self.assertIn((["stale_review_entries"], 0), found)


class ResolvePointerContainerTests(unittest.TestCase):
    def test_root_pointer(self):
        report = {"a": 1}
        self.assertIs(cc.resolve_pointer_container(report, []), report)

    def test_single_level(self):
        report = {"a": 5}
        result = cc.resolve_pointer_container(report, ["a"])
        self.assertEqual(result, {"a": 5})

    def test_nested_returns_parent(self):
        report = {"counts": {"by_category": {"hostname": 20}}}
        result = cc.resolve_pointer_container(report, ["counts", "by_category",
                                                          "hostname"])
        self.assertEqual(result, {"hostname": 20})


# ---------------------------------------------------------------------
# evaluate_claims / discrepancy schema
# ---------------------------------------------------------------------

class EvaluateClaimsTests(unittest.TestCase):
    def test_returns_empty_for_no_claims(self):
        self.assertEqual(cc.evaluate_claims([], {}, "r.json"), [])

    def test_every_discrepancy_has_required_fields(self):
        report = {"confirmed_leaks": [], "reviewed_benign": [
            {"file": "snapshot-diff/README.md", "line": 14,
             "category": "hostname", "verdict": "benign"},
        ]}
        claim = _claim("PRESENCE", token="snapshot-diff/README.md")
        discrepancies = cc.evaluate_claims([claim], report, "r.json")
        self.assertEqual(len(discrepancies), 1)
        d = discrepancies[0]
        required = ("readme_path", "readme_line", "readme_quote",
                    "report_path", "json_pointer", "report_excerpt")
        for field in required:
            self.assertIn(field, d)
            self.assertIsNotNone(d[field])

    def test_matched_claims_produce_no_discrepancy(self):
        report = {"confirmed_leaks": [{"file": "a.py", "line": 1,
                                        "category": "hostname"}]}
        claim = _claim("PRESENCE", token="a.py")
        self.assertEqual(cc.evaluate_claims([claim], report, "r.json"), [])


# ---------------------------------------------------------------------
# Report discovery
# ---------------------------------------------------------------------

class DiscoverReportTests(unittest.TestCase):
    def test_unique_shaped_report(self):
        text = cc.read_text_exact(fx("match_tool", "README.md"))
        disc = cc.discover_report(fx("match_tool"), text)
        self.assertEqual(disc.status, "unique")
        self.assertEqual(disc.report_path, fx("match_tool", "report.json"))

    def test_committed_as_narrowing(self):
        require_full_repo(self)
        text = cc.read_text_exact(os.path.join(REPO_ROOT, "env-leak-scanner",
                                                 "README.md"))
        disc = cc.discover_report(os.path.join(REPO_ROOT, "env-leak-scanner"),
                                   text)
        self.assertEqual(disc.status, "unique")
        self.assertTrue(disc.report_path.endswith("leak_report_2026-08-04.json"))

    def test_ambiguous_multiple_candidates(self):
        text = cc.read_text_exact(fx("ambiguous_tool", "README.md"))
        disc = cc.discover_report(fx("ambiguous_tool"), text)
        self.assertEqual(disc.status, "ambiguous")
        self.assertEqual(sorted(disc.candidates),
                          ["report_a.json", "report_b.json"])

    def test_absent_no_json_at_all(self):
        text = cc.read_text_exact(fx("absent_tool", "README.md"))
        disc = cc.discover_report(fx("absent_tool"), text)
        self.assertEqual(disc.status, "absent")
        self.assertIsNone(disc.report_path)

    def test_empty_findings_report_discovered_via_prose(self):
        text = cc.read_text_exact(fx("empty_dir_tool", "README.md"))
        disc = cc.discover_report(fx("empty_dir_tool"), text)
        self.assertEqual(disc.status, "unique")
        self.assertEqual(disc.report_path, fx("empty_dir_tool", "report.json"))

    def test_is_report_shaped_true_for_file_keyed_list(self):
        self.assertTrue(cc.is_report_shaped(
            {"findings": [{"file": "a.py"}]}))

    def test_is_report_shaped_false_for_empty_lists(self):
        self.assertFalse(cc.is_report_shaped({"findings": []}))

    def test_is_report_shaped_false_for_non_dict(self):
        self.assertFalse(cc.is_report_shaped([1, 2, 3]))

    def test_is_report_shaped_false_for_tool_keyed_entries(self):
        self.assertFalse(cc.is_report_shaped(
            {"findings": [{"tool": "x"}]}))

    def test_nonexistent_tool_dir_returns_absent(self):
        disc = cc.discover_report(fx("no_such_tool_dir"), "no json mentioned")
        self.assertEqual(disc.status, "absent")


# ---------------------------------------------------------------------
# run_target
# ---------------------------------------------------------------------

class RunTargetTests(unittest.TestCase):
    def test_missing_readme(self):
        result = cc.run_target(fx("no_such_readme.md"), None)
        self.assertIsNotNone(result.error)
        self.assertEqual(result.claims_checked, 0)

    def test_zero_claims_no_report_needed(self):
        result = cc.run_target(fx("no_claims_tool", "README.md"), None)
        self.assertIsNone(result.error)
        self.assertEqual(result.claims_checked, 0)

    def test_claims_but_no_report_path_is_error(self):
        result = cc.run_target(fx("missing_report_tool", "README.md"), None)
        self.assertIsNotNone(result.error)

    def test_unreadable_report_is_error(self):
        result = cc.run_target(fx("invalid_json_tool", "README.md"),
                                fx("invalid_json_tool", "report.json"))
        self.assertIsNotNone(result.error)

    def test_clean_match_has_no_discrepancies(self):
        result = cc.run_target(fx("match_tool", "README.md"),
                                fx("match_tool", "report.json"))
        self.assertIsNone(result.error)
        self.assertEqual(result.discrepancies, [])
        self.assertEqual(result.claims_checked, 9)

    def test_contradiction_tool_all_claims_fail(self):
        result = cc.run_target(fx("contradiction_tool", "README.md"),
                                fx("contradiction_tool", "report.json"))
        self.assertIsNone(result.error)
        self.assertEqual(len(result.discrepancies), result.claims_checked)

    def test_unicode_tool_matches(self):
        result = cc.run_target(fx("unicode_tool", "README.md"),
                                fx("unicode_tool", "report.json"))
        self.assertIsNone(result.error)
        self.assertEqual(result.discrepancies, [])

    def test_crlf_tool_matches(self):
        result = cc.run_target(fx("crlf_tool", "README.md"),
                                fx("crlf_tool", "report.json"))
        self.assertIsNone(result.error)
        self.assertEqual(result.discrepancies, [])

    def test_empty_readme_zero_claims(self):
        result = cc.run_target(fx("empty_readme_tool", "README.md"),
                                fx("empty_readme_tool", "report.json"))
        self.assertIsNone(result.error)
        self.assertEqual(result.claims_checked, 0)


# ---------------------------------------------------------------------
# render_human / render_json / overall_exit_code
# ---------------------------------------------------------------------

class RenderTests(unittest.TestCase):
    def test_render_json_is_valid_json(self):
        result = cc.run_target(fx("match_tool", "README.md"),
                                fx("match_tool", "report.json"))
        text = cc.render_json([result])
        data = json.loads(text)
        self.assertEqual(data["totals"]["claims_checked"], 9)

    def test_render_json_deterministic_across_calls(self):
        result = cc.run_target(fx("match_tool", "README.md"),
                                fx("match_tool", "report.json"))
        self.assertEqual(cc.render_json([result]), cc.render_json([result]))

    def test_render_human_reports_total(self):
        result = cc.run_target(fx("match_tool", "README.md"),
                                fx("match_tool", "report.json"))
        text = cc.render_human([result])
        self.assertIn("TOTAL: 9 claim(s) checked, 0 discrepancy(ies)", text)

    def test_render_human_shows_error(self):
        result = cc.run_target(fx("missing_report_tool", "README.md"), None)
        text = cc.render_human([result])
        self.assertIn("ERROR", text)

    def test_overall_exit_code_ok(self):
        result = cc.run_target(fx("match_tool", "README.md"),
                                fx("match_tool", "report.json"))
        self.assertEqual(cc.overall_exit_code([result]), cc.EXIT_OK)

    def test_overall_exit_code_discrepancies(self):
        result = cc.run_target(fx("contradiction_tool", "README.md"),
                                fx("contradiction_tool", "report.json"))
        self.assertEqual(cc.overall_exit_code([result]), cc.EXIT_DISCREPANCIES)

    def test_overall_exit_code_error_outranks_discrepancy(self):
        ok_result = cc.run_target(fx("contradiction_tool", "README.md"),
                                   fx("contradiction_tool", "report.json"))
        err_result = cc.run_target(fx("missing_report_tool", "README.md"), None)
        self.assertEqual(cc.overall_exit_code([ok_result, err_result]),
                          cc.EXIT_ERROR)

    def test_overall_exit_code_empty_results(self):
        self.assertEqual(cc.overall_exit_code([]), cc.EXIT_OK)


# ---------------------------------------------------------------------
# list_tool_dirs
# ---------------------------------------------------------------------

class ListToolDirsTests(unittest.TestCase):
    def test_only_dirs_with_readme_included(self):
        with tempfile.TemporaryDirectory() as d:
            os.makedirs(os.path.join(d, "has_readme"))
            with open(os.path.join(d, "has_readme", "README.md"), "w") as fh:
                fh.write("x")
            os.makedirs(os.path.join(d, "no_readme"))
            names = cc.list_tool_dirs(d)
            self.assertEqual(names, ["has_readme"])

    def test_sorted_order(self):
        with tempfile.TemporaryDirectory() as d:
            for name in ("zeta", "alpha", "mid"):
                os.makedirs(os.path.join(d, name))
                with open(os.path.join(d, name, "README.md"), "w") as fh:
                    fh.write("x")
            self.assertEqual(cc.list_tool_dirs(d), ["alpha", "mid", "zeta"])

    def test_missing_root_raises(self):
        with self.assertRaises(cc.CrosscheckError):
            cc.list_tool_dirs("/no/such/root/at/all")


# ---------------------------------------------------------------------
# CLI end-to-end (in-process)
# ---------------------------------------------------------------------

class CliTests(unittest.TestCase):
    def test_readme_report_match_exit_0(self):
        rc, out, err = run_cli(["--readme", fx("match_tool", "README.md"),
                                 "--report", fx("match_tool", "report.json")])
        self.assertEqual(rc, 0)
        self.assertIn("discrepancies: 0", out)

    def test_readme_report_contradiction_exit_1(self):
        rc, out, err = run_cli(["--readme", fx("contradiction_tool", "README.md"),
                                 "--report", fx("contradiction_tool", "report.json")])
        self.assertEqual(rc, 1)

    def test_readme_without_report_is_usage_error(self):
        rc, out, err = run_cli(["--readme", fx("match_tool", "README.md")])
        self.assertEqual(rc, 2)
        self.assertIn("--report", err)

    def test_no_mode_is_usage_error(self):
        rc, out, err = run_cli([])
        self.assertEqual(rc, 2)

    def test_json_flag_emits_valid_json(self):
        rc, out, err = run_cli(["--readme", fx("match_tool", "README.md"),
                                 "--report", fx("match_tool", "report.json"),
                                 "--json"])
        data = json.loads(out)
        self.assertEqual(data["totals"]["claims_checked"], 9)

    def test_output_flag_writes_file(self):
        with tempfile.TemporaryDirectory() as d:
            out_path = os.path.join(d, "sub", "out.json")
            rc, out, err = run_cli(["--readme", fx("match_tool", "README.md"),
                                     "--report", fx("match_tool", "report.json"),
                                     "-o", out_path])
            self.assertEqual(rc, 0)
            self.assertTrue(os.path.isfile(out_path))
            with open(out_path) as fh:
                data = json.load(fh)
            self.assertEqual(data["totals"]["claims_checked"], 9)
            # human-readable still on stdout since --json not also given
            self.assertIn("claims checked: 9", out)

    def test_tool_mode_auto_discovery(self):
        rc, out, err = run_cli(["--root", FIXTURES, "--tool", "match_tool"])
        self.assertEqual(rc, 0)

    def test_all_mode_real_repo_finds_the_contradiction(self):
        require_full_repo(self)
        rc, out, err = run_cli(["--root", REPO_ROOT, "--all", "--json"])
        self.assertEqual(rc, 1)
        data = json.loads(out)
        self.assertEqual(data["totals"]["discrepancies"], 1)

    def test_strict_discovery_turns_ambiguous_into_error(self):
        rc, out, err = run_cli(["--root", FIXTURES, "--tool", "ambiguous_tool"])
        self.assertEqual(rc, 2)

    def test_missing_tool_dir_is_error(self):
        rc, out, err = run_cli(["--root", FIXTURES, "--tool", "nope"])
        self.assertEqual(rc, 2)

    def test_readme_and_tool_mutually_exclusive(self):
        # argparse itself rejects this combination via SystemExit(2), since
        # --readme/--tool/--all are an argparse mutually-exclusive group.
        with self.assertRaises(SystemExit) as ctx:
            run_cli(["--readme", fx("match_tool", "README.md"),
                     "--tool", "match_tool"])
        self.assertEqual(ctx.exception.code, 2)

    def test_help_exits_cleanly(self):
        with self.assertRaises(SystemExit) as ctx:
            run_cli(["--help"])
        self.assertEqual(ctx.exception.code, 0)


class CliSubprocessTests(unittest.TestCase):
    """A handful of true subprocess invocations, matching exactly how the
    README's documented commands are run, so a change to sys.path handling
    or __main__ guarding cannot pass in-process tests while breaking real
    usage."""

    def _run(self, args):
        return subprocess.run(
            [sys.executable, os.path.join(HERE, "crosscheck.py")] + args,
            cwd=HERE, capture_output=True, text=True)

    def test_subprocess_match_exit_0(self):
        proc = self._run(["--readme", "fixtures/match_tool/README.md",
                           "--report", "fixtures/match_tool/report.json"])
        self.assertEqual(proc.returncode, 0)

    def test_subprocess_env_leak_scanner_exit_1(self):
        require_full_repo(self)
        proc = self._run(["--readme", "../env-leak-scanner/README.md",
                           "--report",
                           "../env-leak-scanner/leak_report_2026-08-04.json"])
        self.assertEqual(proc.returncode, 1)
        self.assertIn("snapshot-diff/README.md", proc.stdout)

    def test_subprocess_missing_report_exit_2(self):
        proc = self._run(["--readme", "fixtures/missing_report_tool/README.md",
                           "--report", "fixtures/missing_report_tool/nope.json"])
        self.assertEqual(proc.returncode, 2)

    def test_subprocess_usage_error_exit_2(self):
        proc = self._run([])
        self.assertEqual(proc.returncode, 2)


# ---------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------

class DeterminismTests(unittest.TestCase):
    def test_two_runs_byte_identical(self):
        rc1, out1, _ = run_cli(["--root", REPO_ROOT, "--all", "--json"])
        rc2, out2, _ = run_cli(["--root", REPO_ROOT, "--all", "--json"])
        self.assertEqual(rc1, rc2)
        self.assertEqual(out1, out2)

    def test_dict_construction_order_does_not_affect_output(self):
        report_a = {}
        report_a["confirmed_leaks"] = [{"file": "a.py", "line": 1,
                                         "category": "hostname"}]
        report_a["reviewed_benign"] = []
        report_b = {}
        report_b["reviewed_benign"] = []
        report_b["confirmed_leaks"] = [{"line": 1, "category": "hostname",
                                         "file": "a.py"}]
        claim = _claim("PRESENCE", token="a.py")
        self.assertEqual(
            cc.evaluate_claims([claim], report_a, "r.json"),
            cc.evaluate_claims([claim], report_b, "r.json"))


# ---------------------------------------------------------------------
# The real, confirmed env-leak-scanner contradiction
# ---------------------------------------------------------------------

class RealRepoContradictionTests(unittest.TestCase):
    """Pins the exact contradiction named in the task brief: the README
    claims snapshot-diff/README.md carries a confirmed hostname leak; the
    committed report only has it in reviewed_benign."""

    @classmethod
    def setUpClass(cls):
        cls.readme_path = os.path.join(REPO_ROOT, "env-leak-scanner", "README.md")
        cls.report_path = os.path.join(REPO_ROOT, "env-leak-scanner",
                                        "leak_report_2026-08-04.json")
        if not os.path.isfile(cls.readme_path) or not os.path.isfile(
                cls.report_path):
            raise unittest.SkipTest(
                "env-leak-scanner sources not found next to claim-crosscheck")
        cls.result = cc.run_target(cls.readme_path, cls.report_path)

    def test_no_setup_error(self):
        self.assertIsNone(self.result.error)

    def test_exactly_one_discrepancy(self):
        self.assertEqual(len(self.result.discrepancies), 1)

    def test_discrepancy_is_snapshot_diff_presence(self):
        d = self.result.discrepancies[0]
        self.assertEqual(d["kind"], "PRESENCE")
        self.assertEqual(d["claim_detail"]["token"], "snapshot-diff/README.md")

    def test_readme_quote_matches_source_line_93(self):
        d = self.result.discrepancies[0]
        self.assertEqual(d["readme_line"], 93)
        text = cc.read_text_exact(self.readme_path)
        lines = text.split("\n")
        # line 93 (1-indexed) contains the start of the quote, though the
        # quote itself begins mid-line, right after "...at a time. ".
        self.assertIn("`LIMITATIONS.md`, `REVIEWERS_GUIDE.md`,", lines[92])
        self.assertIn(d["readme_quote"], text)
        idx = text.index(d["readme_quote"])
        self.assertEqual(cc.line_of(text, idx), 93)

    def test_json_pointer_resolves_to_benign_entry(self):
        d = self.result.discrepancies[0]
        report = cc.load_report(self.report_path)
        entry = cc.resolve_pointer(report, d["json_pointer"])
        self.assertEqual(entry["file"], "snapshot-diff/README.md")
        self.assertEqual(entry["verdict"], "benign")

    def test_json_pointer_is_reviewed_benign_bucket(self):
        d = self.result.discrepancies[0]
        self.assertTrue(d["json_pointer"].startswith("/reviewed_benign/"))

    def test_report_excerpt_matches_pointer_target(self):
        d = self.result.discrepancies[0]
        report = cc.load_report(self.report_path)
        entry = cc.resolve_pointer(report, d["json_pointer"])
        self.assertEqual(d["report_excerpt"], cc.excerpt_for_entry(entry))

    def test_confirmed_leaks_has_zero_entries_for_that_file(self):
        report = cc.load_report(self.report_path)
        matches = [e for e in report["confirmed_leaks"]
                   if e.get("file") == "snapshot-diff/README.md"]
        self.assertEqual(matches, [])

    def test_other_four_listed_files_all_confirmed(self):
        # LIMITATIONS.md, REVIEWERS_GUIDE.md, doc-validator/, bundle-index/
        # are the other four subjects of the same sentence -- all TRUE
        # claims, must NOT appear as discrepancies.
        tokens = {d["claim_detail"].get("token")
                  for d in self.result.discrepancies}
        for should_be_true in ("LIMITATIONS.md", "REVIEWERS_GUIDE.md",
                                "doc-validator/", "bundle-index/"):
            self.assertNotIn(should_be_true, tokens)

    def test_exit_code_is_1(self):
        self.assertEqual(cc.overall_exit_code([self.result]), 1)

    def test_fourteen_other_claims_matched(self):
        self.assertEqual(self.result.claims_checked, 15)
        self.assertEqual(len(self.result.discrepancies), 1)


if __name__ == "__main__":
    unittest.main()
