#!/usr/bin/env bash
# Regenerates counts_captured_output.txt. Every record is a real run.
#
# rec() follows this repository's transcript convention with the pipefail
# fix: header line, the real run under `bash -c 'set -o pipefail; ...'`,
# then the real exit status. /bin/sh here is dash, which has no
# `set -o pipefail`, so bash is required and this script says so.
#
# WHY THIS IS NOT NAMED capture.sh, AND WHY ITS OUTPUT IS NOT
# captured_output.txt.
#
# This directory's committed captured_output.txt records three timed runs
# of the full adversarial suite -- two in an original checkout and one in a
# relocated copy -- taken on a machine whose paths (/tmp/build_4/...) no
# longer exist. That transcript is the relocation proof for the suite
# itself and this script cannot reproduce it. Overwriting it would destroy
# real evidence and replace it with different real evidence, which is
# worse than leaving it alone.
#
# The names also matter mechanically, not just editorially:
#   * regen-preflight discovers regenerators by the exact name capture.sh
#     and re-runs each one against its sibling captured_output.txt. A
#     capture.sh here that produced different content would be reported as
#     drift on every run, forever.
#   * transcript-drift and transcript-schema read <tool>/captured_output.txt
#     by that exact name, so this second transcript is additive and does
#     not change what either of them sees.
# Both effects were checked by running those tools before and after, not
# assumed.
set -u

if ! command -v bash >/dev/null 2>&1; then
    echo "capture_counts.sh: bash is required (for 'set -o pipefail')" >&2
    exit 2
fi

cd "$(dirname "$0")" || exit 2
OUT=counts_captured_output.txt

rec() {
    printf '\n=== $ %s ===\n' "$*" >> "$OUT"
    bash -c "set -o pipefail; $*" >> "$OUT" 2>&1
    printf 'exit=%s\n' "$?" >> "$OUT"
}

cat > "$OUT" <<'HDR'
############################################################
# counts_captured_output.txt -- regenerated by capture_counts.sh.
# Every record is a real run: header, real output, real exit.
#
# Subject: readmecounts.py, which compares the numbers THIS README
# states against the numbers this directory actually has.
############################################################

--- unit suite ---
HDR

rec "python3 -m unittest test_readmecounts"

cat >> "$OUT" <<'NOTE1'

--- the real repository, as committed ---
Every claim the README states must equal what the tree has. The expensive
one (RESULTS_DIGEST) is skipped unless asked for, and says so rather than
being silently absent.
NOTE1

rec "python3 readmecounts.py"

cat >> "$OUT" <<'NOTE2'

--- including the digest claim, which runs the suite for real ---
This regenerates fixtures/ and runs test_adversarial.py --digest, then
compares the hash it prints against the one the README's relocation table
records. That table was produced on a different machine, at
/tmp/build_4/..., which no longer exists.
NOTE2

rec "python3 readmecounts.py --with-digest"

cat >> "$OUT" <<'NOTE3'

--- a deliberately stale claim must fail ---
stale_demo.py copies the checkable files to a throwaway path, changes ONE
occurrence of ONE number in the copied README, and runs the checker
against the copy. The original tree is not touched. Because the README
states this number twice, changing one occurrence is caught as an
internal disagreement -- the two places no longer agree with each other,
which is the failure this repository keeps hitting.
NOTE3

rec "python3 stale_demo.py --claim case_count"
rec "python3 stale_demo.py --claim test_count"

cat >> "$OUT" <<'NOTE4'

--- CLI contract ---
Setup errors are exit 2 and say why on stderr. They must not be confused
with exit 1, which means "a claim did not match".
NOTE4

rec "python3 readmecounts.py --root /no/such/dir/zzz"
rec "python3 readmecounts.py --readme /no/such/file/zzz.md"
rec "python3 readmecounts.py -o /no/such/dir/zzz/out.json"

cat >> "$OUT" <<'NOTE5'

--- determinism: two runs, byte-identical JSON ---
NOTE5

rec "python3 readmecounts.py -o /tmp/readmecounts_r1.json --quiet"
rec "python3 readmecounts.py -o /tmp/readmecounts_r2.json --quiet"
rec "cmp /tmp/readmecounts_r1.json /tmp/readmecounts_r2.json && echo BYTE_IDENTICAL_two_runs"
rec "sha256sum /tmp/readmecounts_r1.json /tmp/readmecounts_r2.json"
rec "rm -f /tmp/readmecounts_r1.json /tmp/readmecounts_r2.json; echo cleaned"

cat >> "$OUT" <<'NOTE6'

--- readmecounts.py leaves the tree as it found it ---
`--with-digest` has to generate fixtures/ to run the suite. Two cases,
both real: one where fixtures/ did not exist, and one where it did and
contained a file that must survive. The second case is here because the
first version of measure_results_digest guarded its own rmtree and then
shelled out to a generator that removes the destination itself -- the
directory, and anything in it, was destroyed.
NOTE6

rec "test -e fixtures && echo PRESENT || echo ABSENT"
rec "python3 readmecounts.py --with-digest --quiet; test -e fixtures && echo STILL_THERE || echo fixtures_absent_after"
rec "mkdir -p fixtures && printf 'do not delete\n' > fixtures/CANARY.txt && python3 readmecounts.py --with-digest --quiet; cat fixtures/CANARY.txt"
rec "rm -rf fixtures; echo removed_the_canary_dir_this_script_created"

cat >> "$OUT" <<'NOTE7'

--- and the generator itself still verifies clean ---
Run explicitly rather than left to whatever state a previous record
happened to leave behind. The earlier version of this transcript recorded
`make_fixtures.py --verify` AFTER --with-digest had removed fixtures/, so
it captured a VERIFY FAILED (with an absolute build path in it) under a
heading that said "this confirms it verifies clean".
NOTE7

rec "python3 make_fixtures.py >/dev/null && python3 make_fixtures.py --verify"
rec "rm -rf fixtures; test -e fixtures && echo STILL_THERE || echo fixtures_removed"

printf '\n############################################################\n# END OF TRANSCRIPT\n############################################################\n' >> "$OUT"

rm -rf __pycache__      # created by this script's own runs
echo "capture_counts.sh: wrote $OUT"
