#!/usr/bin/env bash
# Regenerates captured_output.txt. Every record is a real run.
#
# rec() follows this repository's convention with the pipefail fix:
#   header line, the real run under `bash -c 'set -o pipefail; ...'`,
#   then the real exit status. /bin/sh here is dash, which has no
#   `set -o pipefail`, so bash is required and this script says so.
#
# WHAT THIS TRANSCRIPT DELIBERATELY DOES NOT CONTAIN: a full
# `regenpre.py --root ..` run. That regenerates ten sibling transcripts
# in throwaway copies and takes minutes, and it would be recorded here
# as a single opaque exit code. Worse, regenpre's transcripts phase
# discovers every `*/capture.sh` -- including this one -- so a full run
# from inside this file would recurse. regenpre.py excludes its own
# directory by name for exactly that reason (see SELF_DIR), and this
# transcript records the fast, self-contained evidence instead: the unit
# suite, the CLI contract, and a real end-to-end run over the fixture
# repository the tests build. The full repository run's output is
# committed separately as preflight_report.json, with the interpreter it
# was produced on recorded in README.md.
set -u

if ! command -v bash >/dev/null 2>&1; then
    echo "capture.sh: bash is required (for 'set -o pipefail'); not found on PATH" >&2
    exit 2
fi

cd "$(dirname "$0")" || exit 2
OUT=captured_output.txt

rec() {
    printf '\n=== $ %s ===\n' "$*" >> "$OUT"
    bash -c "set -o pipefail; $*" >> "$OUT" 2>&1
    printf 'exit=%s\n' "$?" >> "$OUT"
}

cat > "$OUT" <<'HDR'
############################################################
# captured_output.txt -- regenerated by capture.sh.
# Every record is a real run: header, real output, real exit.
############################################################

--- unit suite ---
HDR

rec "python3 -m unittest test_regenpre"

cat >> "$OUT" <<'NOTE1'

--- CLI contract: usage errors ---
Both must exit 2, and say why on stderr.
NOTE1

rec "python3 regenpre.py --root no_such_dir_xyz"
rec "python3 regenpre.py --phase nonsense --root .."

cat >> "$OUT" <<'NOTE2'

--- end to end over the fixture repository ---
The test module builds a small repository with one manifest entry, one
baseline and one capture.sh. Below it is built in a temp directory and
regenpre is run against it for real -- a clean pass (exit 0), then the
deliberately-broken variant (exit 1). The report is filtered to the
fields that are stable so this record stays reproducible; the raw
report is what the unit tests assert on.
NOTE2

rec "python3 fixture_demo.py"

cat >> "$OUT" <<'NOTE3'

--- the three inventories this tool unifies, counted from the tree ---
NOTE3

rec "python3 inventory_counts.py .."

printf '\n############################################################\n# END OF TRANSCRIPT\n############################################################\n' >> "$OUT"

rm -rf __pycache__
echo "capture.sh: wrote $OUT"
