#!/usr/bin/env python3
"""regenpre.py -- one command that runs every documented regeneration.

WHAT THIS IS FOR

This repository documents three separate families of "regenerate the
committed artifact" command, and before this tool no single command ran
all of them:

  manifest    the `regenerable` entries in report-freshness/manifest.json.
              `report-freshness/freshness.py` already runs these.
  baselines   the tools in regression-checker/baselines.json.
              `regression-checker/coverage_audit.py` already runs these.
  transcripts every `<tool>/capture.sh`. **Nothing ran these.** They are
              the gap this tool closes: ten scripts that regenerate ten
              committed `captured_output.txt` files, with no automated
              check that any of them still produces what is committed.

A reviewer needed at least two commands and had no way at all to check the
third family. This is the one command.

SAFETY: NOTHING RUNS IN YOUR WORKING TREE

`capture.sh` rewrites the committed transcript in place, and the baseline
and manifest generators write report files. So every regeneration here runs
inside a throwaway copy of the repository, and each transcript regeneration
gets its OWN fresh copy -- otherwise regenerating one tool's transcript
would silently change the input another tool's capture.sh reads, and the
second result would depend on the order. The working tree is never written
to, which is checkable: run this, then `git status`.

CLASSIFICATION

Each item lands in exactly one state:

  match           regenerated bytes are identical to the committed bytes
  volatile_only   differs only in fields that are volatile by nature and
                  named explicitly below (wall-clock durations, random
                  temp-directory names). Not a defect.
  environment     differs in a way that tracks the Python interpreter, not
                  the repository -- e.g. the `Python <version>` banner, and
                  unittest's test-id format, which changed in 3.11. A real
                  reproducibility limit, but not repository drift.
  drift           differs in some other way. This is the one that means
                  the committed artifact no longer matches its producer.
  error           the documented command could not run at all.

`volatile_only` is deliberately narrow and every masked pattern is listed
in VOLATILE_PATTERNS, so a reader can see exactly what was hidden. The
number of substitutions made is reported per item -- masking is never
silent.

Usage:
    python3 regenpre.py --root ..                 # everything
    python3 regenpre.py --root .. --phase transcripts
    python3 regenpre.py --root .. --only index-generator,readme-index
    python3 regenpre.py --root .. -o preflight_report.json

Exit codes:
    0  every item is match or volatile_only
    1  at least one item is environment, drift or error
    2  usage error (bad --root, unknown --phase, or an --only
       name that selects nothing -- a run that checked nothing
       must never exit 0)
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

MATCH = "match"
VOLATILE_ONLY = "volatile_only"
ENVIRONMENT = "environment"
DRIFT = "drift"
ERROR = "error"

#: States that do not fail the preflight.
OK_STATES = (MATCH, VOLATILE_ONLY)

#: (name, compiled pattern, replacement). Applied in order. Each is a
#: field that genuinely varies between two honest runs on one machine.
VOLATILE_PATTERNS = [
    # unittest's own wall-clock measurement. The test COUNT is NOT masked:
    # two runs disagreeing on N is real drift and must still be visible.
    ("unittest_duration", re.compile(r"(Ran \d+ tests? in )[0-9.]+s"),
     r"\1<DURATION>s"),
    # tempfile.mkdtemp / TemporaryDirectory names that reach the output
    # because a test prints an error message containing the full path.
    ("tempdir_name", re.compile(r"/tmp/[A-Za-z0-9_.]*?_[A-Za-z0-9_]{6,}"),
     "/tmp/<TEMPDIR>"),
]

#: Differences that track the interpreter rather than the repository.
ENVIRONMENT_PATTERNS = [
    ("python_version", re.compile(r"Python \d+\.\d+\.\d+")),
    # unittest changed its test id rendering in 3.11:
    #   3.10: test_x (module.TestClass) ... ok
    #   3.11: test_x (module.TestClass.test_x) ... ok
    ("unittest_test_id", re.compile(r"^\S+ \(\S+\) \.\.\. ", re.M)),
]


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def normalise(text):
    """Mask the volatile fields. Returns (text, {pattern_name: count})."""
    counts = {}
    for name, pattern, repl in VOLATILE_PATTERNS:
        text, n = pattern.subn(repl, text)
        counts[name] = n
    return text, counts


def classify(committed, regenerated):
    """-> (state, reason, masked_counts)."""
    if committed == regenerated:
        return MATCH, None, {}
    ctext = committed.decode("utf-8", "replace")
    rtext = regenerated.decode("utf-8", "replace")
    cnorm, ccounts = normalise(ctext)
    rnorm, _ = normalise(rtext)
    if cnorm == rnorm:
        return VOLATILE_ONLY, "differs only in masked volatile fields", ccounts
    for name, pattern in ENVIRONMENT_PATTERNS:
        if set(pattern.findall(ctext)) != set(pattern.findall(rtext)):
            return (ENVIRONMENT,
                    "differs in %s, which tracks the interpreter" % name,
                    ccounts)
    return DRIFT, "differs outside every masked or environment field", ccounts


def fresh_copy(root):
    """A throwaway copy of `root`. Caller removes the returned parent."""
    parent = tempfile.mkdtemp(prefix="regenpre_")
    dest = os.path.join(parent, "tree")
    shutil.copytree(root, dest,
                    ignore=shutil.ignore_patterns(".git", "__pycache__"))
    return parent, dest


def read_bytes(path):
    with open(path, "rb") as fh:
        return fh.read()


def run(argv, cwd):
    """-> (returncode, stderr text). Never raises on a nonzero exit."""
    try:
        p = subprocess.run(argv, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=900)
        return p.returncode, p.stderr.decode("utf-8", "replace")[-2000:]
    except FileNotFoundError as exc:
        return None, "command not found: %s" % exc
    except subprocess.TimeoutExpired:
        return None, "timed out"


def item(phase, name, command, state, reason, **extra):
    d = {"phase": phase, "name": name, "command": command,
         "state": state, "reason": reason}
    d.update(extra)
    return d


def _load(path, key, want):
    """Read `key` out of a JSON object, or return an empty `want`.

    Discovery is a lookup, not a validation pass: the phase functions
    below are what report a broken inventory, with a state and a reason.
    So every way this can fail -- unreadable, not JSON, not an object,
    key absent, key of the wrong type -- has to come back as "no names
    here" rather than as an exception. An earlier version caught only
    (ValueError, KeyError, OSError), which let a manifest.json that
    parsed but held a list escape as a TypeError and abort the whole run
    with exit 1: the code this tool documents as "at least one item is
    environment, drift or error". A crash that looks like a finding is
    the exact defect class this file was repaired for.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
    except (OSError, ValueError):
        return want()
    if not isinstance(doc, dict):
        return want()
    value = doc.get(key)
    return value if isinstance(value, want) else want()


def selectable_targets(root, phases):
    """-> {phase: {name, ...}} of every --only value that selects something.

    Discovery only: reads the same three inventories the phase functions
    read and runs nothing. `--only` is a filter over these names, so a
    name that appears in none of them can never select an item -- which is
    why it has to be a usage error rather than an empty, green report.
    """
    found = {}
    if "manifest" in phases:
        path = os.path.join(root, "report-freshness", "manifest.json")
        names = set()
        if os.path.isfile(path):
            entries = _load(path, "entries", list)
            names = {e["tool"] for e in entries
                     if isinstance(e, dict) and e.get("kind") == "regenerable"
                     and isinstance(e.get("tool"), str)}
        found["manifest"] = names
    if "baselines" in phases:
        path = os.path.join(root, "regression-checker", "baselines.json")
        names = set()
        if os.path.isfile(path):
            names = {t for t in _load(path, "tools", dict) if isinstance(t, str)}
        found["baselines"] = names
    if "transcripts" in phases:
        try:
            # sorted() only for tidiness -- the result is a set, so
            # listdir order cannot reach the output. Written this way so
            # this line does not add an ND002 finding to the repository's
            # own nondeterminism self-scan for a difference that has no
            # observable effect.
            names = {d for d in sorted(os.listdir(root))
                     if os.path.isfile(os.path.join(root, d, "capture.sh"))}
        except OSError:
            names = set()
        found["transcripts"] = names
    return found


def check_manifest(root, only):
    path = os.path.join(root, "report-freshness", "manifest.json")
    if not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as fh:
        entries = json.load(fh)["entries"]
    out = []
    for e in sorted(entries, key=lambda e: e["id"]):
        if e.get("kind") != "regenerable":
            continue
        name = e["id"]
        if only and e["tool"] not in only:
            continue
        argv = list(e["generation"]["argv"])
        cwd_rel = e["generation"]["cwd"]
        parent, tree = fresh_copy(root)
        try:
            outfile = os.path.join(parent, "out.json")
            argv = [outfile if a == "{OUT}" else a for a in argv]
            rc, err = run(argv, os.path.join(tree, cwd_rel))
            committed_path = os.path.join(root, e["committed_report"])
            if rc is None or not os.path.isfile(outfile):
                out.append(item("manifest", name, argv, ERROR,
                                err.strip() or "no report produced",
                                exit_code=rc,
                                expected_exit_code=e.get("expected_exit_code")))
                continue
            state, reason, masked = classify(read_bytes(committed_path),
                                             read_bytes(outfile))
            out.append(item("manifest", name, argv, state, reason,
                            exit_code=rc,
                            expected_exit_code=e.get("expected_exit_code"),
                            masked=masked))
        finally:
            shutil.rmtree(parent)
    return out


def check_baselines(root, only):
    path = os.path.join(root, "regression-checker", "baselines.json")
    if not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as fh:
        tools = json.load(fh)["tools"]
    out = []
    for tool in sorted(tools):
        if only and tool not in only:
            continue
        spec = tools[tool]
        parent, tree = fresh_copy(root)
        try:
            report = os.path.join(parent, "report.json")
            argv = [report if a == "{REPORT}" else a for a in spec["command"]]
            rc, err = run(argv, os.path.join(tree, tool))
            expected_rc = spec.get("expected_exit_code")
            if rc is None or not os.path.isfile(report):
                out.append(item("baselines", tool, argv, ERROR,
                                err.strip().splitlines()[-1] if err.strip()
                                else "no report produced",
                                exit_code=rc, expected_exit_code=expected_rc))
                continue
            digest = sha256_bytes(read_bytes(report))
            if rc != expected_rc:
                state, reason = DRIFT, "exit code %s, baseline expects %s" % (
                    rc, expected_rc)
            elif digest != spec.get("expected_report_sha256"):
                state, reason = DRIFT, "report sha256 differs from baseline"
            else:
                state, reason = MATCH, None
            out.append(item("baselines", tool, argv, state, reason,
                            exit_code=rc, expected_exit_code=expected_rc,
                            sha256=digest))
        finally:
            shutil.rmtree(parent)
    return out


#: This tool's own directory name. Its capture.sh runs regenpre.py, so
#: regenerating its transcript from inside the transcripts phase would
#: recurse: regenpre -> capture.sh -> regenpre -> ... Excluded by name, and
#: reported as such rather than silently dropped.
SELF_DIR = os.path.basename(os.path.dirname(os.path.abspath(__file__)))


def check_transcripts(root, only):
    tools = sorted(d for d in os.listdir(root)
                   if os.path.isfile(os.path.join(root, d, "capture.sh")))
    out = []
    for tool in tools:
        if only and tool not in only:
            continue
        if tool == SELF_DIR:
            out.append(item("transcripts", tool, ["bash", "capture.sh"],
                            MATCH,
                            "skipped: this is regenpre's own directory and "
                            "its capture.sh runs regenpre, which would recurse",
                            skipped=True))
            continue
        committed_path = os.path.join(root, tool, "captured_output.txt")
        if not os.path.isfile(committed_path):
            out.append(item("transcripts", tool, ["bash", "capture.sh"], ERROR,
                            "capture.sh exists but captured_output.txt does not"))
            continue
        # Each transcript gets its OWN copy: regenerating one tool's
        # transcript changes an input other tools read, so sharing a copy
        # would make results order-dependent.
        parent, tree = fresh_copy(root)
        try:
            rc, err = run(["bash", "capture.sh"], os.path.join(tree, tool))
            produced = os.path.join(tree, tool, "captured_output.txt")
            if rc is None or not os.path.isfile(produced):
                out.append(item("transcripts", tool, ["bash", "capture.sh"],
                                ERROR, err.strip() or "no transcript produced",
                                exit_code=rc))
                continue
            state, reason, masked = classify(read_bytes(committed_path),
                                             read_bytes(produced))
            out.append(item("transcripts", tool, ["bash", "capture.sh"],
                            state, reason, exit_code=rc, masked=masked))
        finally:
            shutil.rmtree(parent)
    return out


PHASES = {
    "manifest": check_manifest,
    "baselines": check_baselines,
    "transcripts": check_transcripts,
}


def build_report(root, phases, only):
    items = []
    for phase in phases:
        items.extend(PHASES[phase](root, only))
    items.sort(key=lambda d: (d["phase"], d["name"]))
    counts = {s: 0 for s in (MATCH, VOLATILE_ONLY, ENVIRONMENT, DRIFT, ERROR)}
    for it in items:
        counts[it["state"]] += 1
    return {
        "schema_version": 1,
        "tool": "regenpre",
        "phases": sorted(phases),
        "counts": counts,
        "total": len(items),
        "failing": sum(counts[s] for s in counts if s not in OK_STATES),
        "volatile_patterns": [n for n, _, _ in VOLATILE_PATTERNS],
        "environment_patterns": [n for n, _ in ENVIRONMENT_PATTERNS],
        "items": items,
    }


def canonical_json(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=True) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(prog="regenpre.py")
    ap.add_argument("--root", default="..", help="repository root (default: ..)")
    ap.add_argument("--phase", action="append",
                    help="restrict to a phase; repeatable. One of: %s"
                         % ", ".join(sorted(PHASES)))
    ap.add_argument("--only", help="comma-separated tool names to include")
    ap.add_argument("-o", "--output", help="write the JSON report here")
    args = ap.parse_args(argv)

    if not os.path.isdir(args.root):
        sys.stderr.write("regenpre.py: --root is not a directory: %s\n"
                         % args.root)
        return 2
    phases = args.phase or sorted(PHASES)
    unknown = [p for p in phases if p not in PHASES]
    if unknown:
        sys.stderr.write("regenpre.py: unknown --phase: %s\n"
                         % ", ".join(unknown))
        return 2
    only = None
    if args.only:
        # `--only ""` is NOT rejected: at every previous commit an empty
        # string was falsy here, so it meant "no filter" and the run
        # checked everything. Turning that into an error would change the
        # findings path -- a drifting repository would stop exiting 1 --
        # which is a different bug, not a fix. `--only ","` or `--only
        # "  "` are a different matter: they are non-empty strings that
        # name nothing, they DID produce the silent green report, and
        # they are rejected below.
        only = set(x.strip() for x in args.only.split(",") if x.strip())
        root_abs = os.path.abspath(args.root)
        # Validated against EVERY phase, not just the selected ones, so
        # that the two failure modes get different messages: a name this
        # repository has never heard of, versus a real name that the
        # chosen --phase cannot select.
        everywhere = selectable_targets(root_abs, set(PHASES))
        known_all = set().union(*everywhere.values()) if everywhere else set()
        if not only:
            sys.stderr.write(
                "regenpre.py: --only %r names nothing after splitting on "
                "commas; it would select no items and the run would report "
                "success having checked nothing. Omit --only to check "
                "everything.\n" % args.only)
            return 2
        unknown = sorted(only - known_all)
        if unknown:
            sys.stderr.write(
                "regenpre.py: unknown --only: %s\n"
                "  --only filters the names this repository actually "
                "offers; a name that matches none of them selects no "
                "items, and a run that checked nothing must not exit 0.\n"
                "  known names: %s\n"
                % (", ".join(unknown),
                   ", ".join(sorted(known_all)) or "(none discovered)"))
            return 2
        here = selectable_targets(root_abs, set(phases))
        selectable = set().union(*here.values()) if here else set()
        if not (only & selectable):
            sys.stderr.write(
                "regenpre.py: --only %s selects nothing in phase(s) %s\n"
                "  those names exist, but not in the phases requested, so "
                "this run would check nothing and report success.\n"
                "  selectable there: %s\n"
                % (", ".join(sorted(only)), ", ".join(sorted(phases)),
                   ", ".join(sorted(selectable)) or "(none)"))
            return 2

    report = build_report(os.path.abspath(args.root), phases, only)
    text = canonical_json(report)
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)
    return 1 if report["failing"] else 0


if __name__ == "__main__":
    sys.exit(main())
