#!/usr/bin/env python3
"""freshness.py -- stdlib-only report-freshness checker.

Regenerates the *regenerable* report artifacts named in `manifest.json`,
using each entry's own offline generation command, and compares the
regenerated bytes against the committed report byte-for-byte. For
*pinned* entries -- point-in-time evidence that must never be
regenerated -- it verifies existence and records the committed SHA-256
and byte length instead. It answers one of two questions per manifest
entry, depending on `kind`:

  regenerable:  *does the committed report still reproduce?*
  pinned:       *is the committed evidence file still there, unaltered?*

This tool exists because reports in this repository have gone stale
without anyone noticing:

  * `regression-checker/baseline_coverage_report.json` enumerated 45 tool
    directories. A 46th directory (`claim-crosscheck/`) was added later
    and the committed report stopped reproducing -- plus tests that
    hardcoded the old directory/baseline counts started failing.
  * `claim-crosscheck/sample_run.json` enumerates every tool directory's
    README/report pair. Adding `report-freshness/` (this directory) is
    exactly the kind of change that can flip its report discovery
    (ambiguous vs. unambiguous), which changes the committed bytes.

Both were caught only by re-running the generator and diffing bytes --
which is precisely what this script automates for entries where that is
the right question to ask at all.

Not every committed report SHOULD regenerate, though
------------------------------------------------------
Two artifacts in this repository are point-in-time evidence, not
current-state snapshots:

  * `env-leak-scanner/leak_report_2026-08-04.json` -- the date is in the
    filename. It is a scan of the repository as it looked on that date.
    Regenerating it against today's tree does not "refresh" it, it
    destroys the thing it was committed to record.
  * `transcript-drift/drift_report_after_migration.json` -- the "after"
    half of a committed before/after pair documenting one specific
    migration that ran at one specific commit. A before/after pair whose
    "after" half gets regenerated later against an unrelated tree stops
    meaning anything.

Flagging either of those `stale` would be actively misleading -- it
would train a reviewer to ignore a real, correct "stale" finding on a
report that never should have been touched at all. `kind: "pinned"`
exists so the manifest can say, explicitly, which artifacts are current
state and which are frozen record, instead of the checker guessing.

Seven states, one per manifest entry
--------------------------------------
  For `kind: "regenerable"`:
    match              regenerated bytes are byte-identical to committed
    stale              generation succeeded (expected exit code, output
                        produced) but the bytes differ from committed
    missing            generation succeeded but no committed report
                        exists at the declared path
    generation_failed  the command could not be launched, timed out,
                        exited with an unexpected code, or produced no
                        output file at all
    tool_missing       the tool directory itself is absent, or the
                        script the manifest names inside it is absent --
                        generation was never attempted

  For `kind: "pinned"` (the generator is NEVER invoked):
    pinned_present      the committed evidence file exists; its SHA-256
                        and byte length are recorded, nothing is compared
    pinned_missing      the committed evidence file is gone -- this IS an
                        error state, not a shrug: deleted evidence is a
                        real problem

A generator that exits nonzero **as documented** in a regenerable
entry's `expected_exit_code` is not a failure. `regression-checker`,
`claim-crosscheck` and `transcript-schema` are all expected to exit 1
(by design -- see their READMEs); only an exit code that does NOT match
`expected_exit_code` is `generation_failed`.

Exit codes (of this script)
----------------------------
    0  every manifest entry is "match" or "pinned_present"
    1  ran to completion; at least one regenerable entry is "stale" or
       "missing" (a real, checkable finding -- nothing crashed)
    2  setup error: manifest missing/unreadable/malformed, --root not a
       directory, or --output could not be written. No entries were
       checked.
    3  at least one entry is "generation_failed", "tool_missing", or
       "pinned_missing" -- freshness/integrity of that entry could not
       even be determined, or committed evidence is gone

`3` outranks `1`: an entry that could not be evaluated at all, or whose
evidence has vanished, is reported ahead of "merely" stale content.

Path independence
------------------
Nothing derived from the *value* of --root (an absolute path) is ever
written into the JSON report. Only repository-relative strings taken
directly from the manifest (tool names, the committed_report path, the
generation cwd, argv tokens, input paths) appear in the output, and the
manifest itself never contains absolute paths. Subprocess stdout/stderr
is deliberately discarded rather than embedded in the report, because a
traceback can contain the absolute path of the interpreter or script
that failed to launch. Iteration is always over entries sorted by `id`.
There is no clock read anywhere in this file.

Regeneration never touches the working tree
----------------------------------------------
Every regenerated artifact is written under a fresh `tempfile` directory
created by this script (outside the repository), never over the
committed report. The committed report is only ever opened for reading.
Pinned entries never invoke a subprocess at all.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile

SCHEMA_VERSION = 2
TOOL_NAME = "report-freshness"
DEFAULT_TIMEOUT = 120
MANIFEST_PATH_LABEL = "report-freshness/manifest.json"
OUT_PLACEHOLDER = "{OUT}"

KIND_REGENERABLE = "regenerable"
KIND_PINNED = "pinned"
ALL_KINDS = (KIND_REGENERABLE, KIND_PINNED)

STATE_MATCH = "match"
STATE_STALE = "stale"
STATE_MISSING = "missing"
STATE_GENERATION_FAILED = "generation_failed"
STATE_TOOL_MISSING = "tool_missing"
STATE_PINNED_PRESENT = "pinned_present"
STATE_PINNED_MISSING = "pinned_missing"

ALL_STATES = (
    STATE_MATCH,
    STATE_STALE,
    STATE_MISSING,
    STATE_GENERATION_FAILED,
    STATE_TOOL_MISSING,
    STATE_PINNED_PRESENT,
    STATE_PINNED_MISSING,
)


class SetupError(Exception):
    """A problem with the checker's own setup (bad manifest, bad --root,
    unwritable --output). Maps to exit code 2. No entry's freshness is
    implied by this exception -- the check never started."""


# --------------------------------------------------------------------------
# Canonical JSON (matches the convention used across this repository's
# other stdlib tools: sorted keys, tight separators, ASCII-only, one
# trailing newline, byte-identical across machines for identical input).
# --------------------------------------------------------------------------

def canonical_json(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n"


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def is_exit_code(value):
    """True only for a real (non-bool) integer. `isinstance(True, int)` is
    True in Python, so a naive check would accept a manifest entry with
    `"expected_exit_code": false` and later compare it equal to a real
    exit code of 0. Rejected explicitly, never coerced."""
    return isinstance(value, int) and not isinstance(value, bool)


# --------------------------------------------------------------------------
# Manifest loading and strict validation
# --------------------------------------------------------------------------

def _require(cond, message):
    if not cond:
        raise SetupError(message)


def load_manifest(path):
    """Load and strictly validate manifest.json. Raises SetupError on any
    structural problem. Returns a list of normalized entry dicts, in the
    order they appeared in the file (callers sort by id before use)."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw_text = fh.read()
    except OSError as exc:
        raise SetupError("could not read manifest %s: %s" % (path, exc.strerror or exc))

    try:
        doc = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        raise SetupError("manifest %s is not valid JSON: %s" % (path, exc))

    _require(isinstance(doc, dict), "manifest %s: top level must be a JSON object" % path)
    _require("entries" in doc, "manifest %s: missing required key 'entries'" % path)
    entries_raw = doc["entries"]
    _require(isinstance(entries_raw, list), "manifest %s: 'entries' must be a JSON array" % path)
    _require(len(entries_raw) > 0, "manifest %s: 'entries' must not be empty" % path)

    seen_ids = set()
    entries = []
    for index, raw in enumerate(entries_raw):
        entries.append(_validate_entry(path, index, raw, seen_ids))
    return entries


def _validate_generation(where, generation, require_out_placeholder):
    _require(isinstance(generation, dict), "%s 'generation' must be a JSON object" % where)
    _require("argv" in generation, "%s 'generation' missing 'argv'" % where)
    _require("cwd" in generation, "%s 'generation' missing 'cwd'" % where)

    argv = generation["argv"]
    _require(isinstance(argv, list) and len(argv) > 0, "%s 'generation.argv' must be a non-empty JSON array" % where)
    for tok in argv:
        _require(isinstance(tok, str), "%s 'generation.argv' must contain only strings" % where)
    if require_out_placeholder:
        _require(
            any(OUT_PLACEHOLDER in tok for tok in argv),
            "%s 'generation.argv' must contain the %s placeholder somewhere" % (where, OUT_PLACEHOLDER),
        )

    cwd = generation["cwd"]
    _require(isinstance(cwd, str) and cwd, "%s 'generation.cwd' must be a non-empty string" % where)
    _require(not os.path.isabs(cwd), "%s 'generation.cwd' must be repository-relative, not absolute" % where)

    return {"argv": list(argv), "cwd": cwd}


def _validate_entry(path, index, raw, seen_ids):
    where = "manifest %s: entries[%d]" % (path, index)
    _require(isinstance(raw, dict), "%s must be a JSON object" % where)

    for key in ("id", "tool", "kind", "committed_report"):
        _require(key in raw, "%s missing required key %r" % (where, key))

    entry_id = raw["id"]
    _require(isinstance(entry_id, str) and entry_id, "%s 'id' must be a non-empty string" % where)
    _require(entry_id not in seen_ids, "%s duplicate id %r" % (where, entry_id))
    seen_ids.add(entry_id)
    where = "manifest %s: entry %r" % (path, entry_id)

    tool = raw["tool"]
    _require(isinstance(tool, str) and tool, "%s 'tool' must be a non-empty string" % where)
    _require("/" not in tool and "\\" not in tool, "%s 'tool' must be a single path component, got %r" % (where, tool))

    kind = raw["kind"]
    _require(
        isinstance(kind, str) and kind in ALL_KINDS,
        "%s 'kind' must be one of %r, got %r" % (where, ALL_KINDS, kind),
    )

    committed_report = raw["committed_report"]
    _require(
        isinstance(committed_report, str) and committed_report,
        "%s 'committed_report' must be a non-empty string" % where,
    )
    _require(
        not os.path.isabs(committed_report),
        "%s 'committed_report' must be repository-relative, not absolute" % where,
    )

    if kind == KIND_REGENERABLE:
        _require("generation" in raw, "%s kind is 'regenerable' but 'generation' is missing" % where)
        _require(
            "expected_exit_code" in raw,
            "%s kind is 'regenerable' but 'expected_exit_code' is missing" % where,
        )
        generation = _validate_generation(where, raw["generation"], require_out_placeholder=True)
        expected_exit_code = raw["expected_exit_code"]
        _require(
            is_exit_code(expected_exit_code),
            "%s 'expected_exit_code' must be a JSON integer (not a boolean), got %r" % (where, expected_exit_code),
        )
    else:  # KIND_PINNED -- generation/expected_exit_code are optional provenance only,
        # NEVER executed. A pinned entry that omits them entirely is fully valid.
        if "generation" in raw and raw["generation"] is not None:
            generation = _validate_generation(where, raw["generation"], require_out_placeholder=False)
        else:
            generation = None
        if "expected_exit_code" in raw and raw["expected_exit_code"] is not None:
            expected_exit_code = raw["expected_exit_code"]
            _require(
                is_exit_code(expected_exit_code),
                "%s 'expected_exit_code' must be a JSON integer (not a boolean) if present, got %r"
                % (where, expected_exit_code),
            )
        else:
            expected_exit_code = None

    inputs = raw.get("inputs", [])
    _require(isinstance(inputs, list), "%s 'inputs' must be a JSON array if present" % where)
    for tok in inputs:
        _require(isinstance(tok, str), "%s 'inputs' must contain only strings" % where)

    description = raw.get("description")
    if description is not None:
        _require(isinstance(description, str), "%s 'description' must be a string if present" % where)

    return {
        "id": entry_id,
        "tool": tool,
        "kind": kind,
        "description": description,
        "generation": generation,
        "committed_report": committed_report,
        "expected_exit_code": expected_exit_code,
        "inputs": list(inputs),
    }


# --------------------------------------------------------------------------
# Per-entry evaluation
# --------------------------------------------------------------------------

def _safe_dirname(entry_id):
    return "".join(ch if (ch.isalnum() or ch in "-_.") else "_" for ch in entry_id)


def tool_missing_reason(root_abs, entry):
    """Return a human reason string if the tool directory or the script
    the manifest names inside it does not exist, else None. Checked
    BEFORE attempting to execute anything, so a missing tool is never
    confused with 'ran and failed'. Only called for regenerable entries
    (pinned entries have no generation to run at all)."""
    cwd_rel = entry["generation"]["cwd"]
    cwd_abs = os.path.join(root_abs, cwd_rel)
    if not os.path.isdir(cwd_abs):
        return "tool directory '%s' does not exist" % cwd_rel
    for tok in entry["generation"]["argv"]:
        if tok.endswith(".py"):
            script_abs = os.path.join(cwd_abs, tok)
            if not os.path.isfile(script_abs):
                return "generation script '%s' not found in '%s'" % (tok, cwd_rel)
            break
    return None


def read_committed(root_abs, entry):
    abs_path = os.path.join(root_abs, entry["committed_report"])
    if not os.path.isfile(abs_path):
        return None
    with open(abs_path, "rb") as fh:
        return fh.read()


def run_generation(root_abs, entry, temp_root, timeout):
    """Run the entry's generation command with {OUT} substituted for a
    fresh path under temp_root (outside the repository). Never raises --
    all failure modes are captured in the returned dict. Only ever called
    for `kind: "regenerable"` entries; pinned entries never reach this
    function.

    Returned dict keys:
        launch_error_kind  str or None  (exception class name only, never
                                          the exception text, so no
                                          absolute path can leak through it)
        timed_out           bool
        exit_code           int or None
        output_bytes        bytes or None
    """
    cwd_abs = os.path.join(root_abs, entry["generation"]["cwd"])
    out_dir = os.path.join(temp_root, _safe_dirname(entry["id"]))
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "regenerated_output")
    argv = [tok.replace(OUT_PLACEHOLDER, out_path) for tok in entry["generation"]["argv"]]

    result = {
        "launch_error_kind": None,
        "timed_out": False,
        "exit_code": None,
        "output_bytes": None,
    }
    try:
        proc = subprocess.run(
            argv,
            cwd=cwd_abs,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
        result["exit_code"] = proc.returncode
    except subprocess.TimeoutExpired:
        result["timed_out"] = True
        return result
    except OSError as exc:
        result["launch_error_kind"] = type(exc).__name__
        return result

    if os.path.isfile(out_path):
        with open(out_path, "rb") as fh:
            result["output_bytes"] = fh.read()
    return result


def classify_regenerable(entry, tool_missing_msg, gen_result, committed_bytes, timeout):
    """Pure decision function for a `kind: "regenerable"` entry: given
    everything already gathered about it, return (state, reason_or_None).
    No filesystem/subprocess access happens in here -- this is the piece
    unit tests exercise directly with synthetic inputs."""
    if tool_missing_msg is not None:
        return STATE_TOOL_MISSING, tool_missing_msg

    expected = entry["expected_exit_code"]

    if gen_result["launch_error_kind"] is not None:
        return STATE_GENERATION_FAILED, "command could not be launched (%s)" % gen_result["launch_error_kind"]

    if gen_result["timed_out"]:
        return STATE_GENERATION_FAILED, "command timed out after %ds" % timeout

    actual = gen_result["exit_code"]
    if actual != expected:
        return (
            STATE_GENERATION_FAILED,
            "generation command exited %r, expected %r" % (actual, expected),
        )

    if gen_result["output_bytes"] is None:
        return (
            STATE_GENERATION_FAILED,
            "generation command exited %r as expected but produced no output file" % expected,
        )

    if committed_bytes is None:
        return STATE_MISSING, "no committed report at the declared path"

    if committed_bytes == gen_result["output_bytes"]:
        return STATE_MATCH, None

    return STATE_STALE, "regenerated bytes differ from the committed report"


def classify_pinned(committed_bytes):
    """Pure decision function for a `kind: "pinned"` entry. The generator
    is never invoked; only existence is checked."""
    if committed_bytes is None:
        return STATE_PINNED_MISSING, "pinned evidence file is missing from the declared path"
    return STATE_PINNED_PRESENT, None


_EMPTY_GEN_RESULT = {"launch_error_kind": None, "timed_out": False, "exit_code": None, "output_bytes": None}


def evaluate_entry(root_abs, entry, temp_root, timeout):
    committed_bytes = read_committed(root_abs, entry)
    generation = entry.get("generation")

    if entry["kind"] == KIND_PINNED:
        # NEVER run the generator for a pinned entry. This is the whole
        # point of "pinned": point-in-time evidence must not be touched.
        state, reason = classify_pinned(committed_bytes)
        generator_invoked = False
        gen_result = _EMPTY_GEN_RESULT
    else:
        tm_reason = tool_missing_reason(root_abs, entry)
        if tm_reason is not None:
            gen_result = _EMPTY_GEN_RESULT
            generator_invoked = False
        else:
            gen_result = run_generation(root_abs, entry, temp_root, timeout)
            generator_invoked = True
        state, reason = classify_regenerable(entry, tm_reason, gen_result, committed_bytes, timeout)

    regenerated_bytes = gen_result["output_bytes"]
    return {
        "id": entry["id"],
        "tool": entry["tool"],
        "kind": entry["kind"],
        "description": entry.get("description"),
        "state": state,
        "reason": reason,
        "committed_report": entry["committed_report"],
        "committed_present": committed_bytes is not None,
        "committed_sha256": sha256_hex(committed_bytes) if committed_bytes is not None else None,
        "committed_bytes": len(committed_bytes) if committed_bytes is not None else None,
        "generator_invoked": generator_invoked,
        "regenerated_sha256": sha256_hex(regenerated_bytes) if regenerated_bytes is not None else None,
        "regenerated_bytes": len(regenerated_bytes) if regenerated_bytes is not None else None,
        "expected_exit_code": entry.get("expected_exit_code"),
        "actual_exit_code": gen_result["exit_code"],
        "generation_argv": generation["argv"] if generation else None,
        "generation_cwd": generation["cwd"] if generation else None,
        "inputs": entry["inputs"],
    }


# --------------------------------------------------------------------------
# Report assembly
# --------------------------------------------------------------------------

def build_report(manifest_path, root, timeout):
    root_abs = os.path.abspath(root)
    if not os.path.isdir(root_abs):
        raise SetupError("--root %r is not a directory" % root)

    entries = load_manifest(manifest_path)
    entries_sorted = sorted(entries, key=lambda e: e["id"])

    counts = {state: 0 for state in ALL_STATES}
    results = []
    with tempfile.TemporaryDirectory(prefix="report_freshness_") as temp_root:
        for entry in entries_sorted:
            result = evaluate_entry(root_abs, entry, temp_root, timeout)
            counts[result["state"]] += 1
            results.append(result)

    counts["total"] = len(results)

    if counts[STATE_GENERATION_FAILED] > 0 or counts[STATE_TOOL_MISSING] > 0 or counts[STATE_PINNED_MISSING] > 0:
        exit_code = 3
    elif counts[STATE_STALE] > 0 or counts[STATE_MISSING] > 0:
        exit_code = 1
    else:
        exit_code = 0

    report = {
        "schema_version": SCHEMA_VERSION,
        "tool": TOOL_NAME,
        "manifest_path": MANIFEST_PATH_LABEL,
        "counts": counts,
        "entries": results,
    }
    return report, exit_code


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def build_arg_parser():
    p = argparse.ArgumentParser(
        prog="freshness.py",
        description="Regenerate configured regenerable report artifacts and compare their "
        "exact bytes with the committed versions; verify pinned evidence files exist "
        "without ever regenerating them.",
    )
    p.add_argument(
        "--manifest",
        default=None,
        help="path to manifest.json (default: manifest.json next to this script)",
    )
    p.add_argument(
        "--root",
        default="..",
        help="repository root that manifest 'generation.cwd' and 'committed_report' paths "
        "are relative to (default: ..)",
    )
    p.add_argument("-o", "--output", default=None, help="write the report JSON here instead of stdout")
    p.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_TIMEOUT,
        help="per-entry subprocess timeout in seconds, regenerable entries only (default: %d)" % DEFAULT_TIMEOUT,
    )
    return p


def _write_text(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def main(argv=None):
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    manifest_path = args.manifest
    if manifest_path is None:
        manifest_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "manifest.json")

    try:
        report, exit_code = build_report(manifest_path, args.root, args.timeout)
        text = canonical_json(report)
        if args.output:
            try:
                _write_text(args.output, text)
            except OSError as exc:
                raise SetupError("could not write --output %s: %s" % (args.output, exc))
        else:
            sys.stdout.write(text)
        return exit_code
    except SetupError as exc:
        error_report = {
            "schema_version": SCHEMA_VERSION,
            "tool": TOOL_NAME,
            "status": "error",
            "error": str(exc),
        }
        text = canonical_json(error_report)
        sys.stderr.write("freshness: setup error: %s\n" % exc)
        if args.output:
            try:
                _write_text(args.output, text)
            except OSError:
                sys.stderr.write(text)
        else:
            sys.stdout.write(text)
        return 2


if __name__ == "__main__":
    sys.exit(main())
