#!/usr/bin/env bash
# Regenerates EXIT_CODE_EVIDENCE.txt. Run from inside reward-reconciler/.
#
# Deliberately NOT named capture.sh. regen-preflight discovers regenerators by
# that exact name and re-runs each one inside a copy of the tree made with
# copytree(..., ignore=ignore_patterns(".git", "__pycache__")). This script
# reads Git history -- it needs the pre-fix source to run the table against --
# so in that copy it could not work, and naming it capture.sh would turn a
# correct script into a preflight failure. captured_output.txt, which this
# directory has had since it was written, is regenerated by
# mk_captured_output.sh instead, for the same reason plus the unittest
# wall-clock in it.
#
# PARENT is the tree this fix landed on. Hard-coded rather than HEAD~1 so the
# "before" column keeps naming the same source no matter what is committed
# afterwards. Override it to re-measure against a different tree.
PARENT=${PARENT:-c373d7c40fbd6610faf4cabad86a5b871c3d192d}
out=EXIT_CODE_EVIDENCE.txt
scratch=_exitcode_scratch

# bash, not sh: `set -o pipefail` is what makes a piped record's exit= line
# report the failing command rather than the exit status of `tail`. /bin/sh
# here is dash and has no pipefail.
rec() {
  printf '=== $ %s ===\n' "$1" >> "$out"
  bash -c "set -o pipefail; $1" >> "$out" 2>&1
  printf 'exit=%s\n\n' "$?" >> "$out"
}

rm -rf "$scratch"
mkdir -p "$scratch"
cat > "$out" <<'HDR'
reward-reconciler -- documented exit code evidence
==================================================

Records use transcript-drift/FORMAT.md's grammar: a "=== $ command ===" header,
the verbatim output, and an exit= line. All paths are relative. Records run
under `bash -c 'set -o pipefail; ...'`, so a piped record's exit= line reports
the command that failed rather than the exit status of `tail`.

This file DEPARTS from FORMAT.md in one respect, deliberately: it commits
`FAILED` verdicts. FORMAT.md classifies a committed FAILED as drift by
definition, and it is right to -- for captured_output.txt, which is a claim
that the tool works. This file is the opposite claim: that the tool did NOT
honour its documented exit codes before the fix. The repository's validators
only ever read captured_output.txt, so nothing here is being smuggled past a
gate; the departure is stated because a file claiming conformance while
violating a rule is worse than one that says which rule it breaks and why.

What this proves, in order:

  1. the pre-fix source, read out of Git, returns the WRONG code for five
     documented conditions -- and returns it by crashing, so the exit status
     is 1, which README.md defines as "mismatched, one or more settlement
     issues";
  2. the same test file, run against that source, fails;
  3. the fixed source returns the documented code for every case in the
     table, with no traceback anywhere;
  4. the valid inputs still reconcile to the committed report.

The one number here that is not reproducible is the wall-clock in unittest's
`Ran N tests in ...s` line. Everything else -- exit codes, error codes,
counts, verdicts -- is fixed by construction.

HDR
rec "echo $PARENT"
rec "git cat-file -t $PARENT"
rec "git show $PARENT:reward-reconciler/reconcile.py > $scratch/reconcile.py && wc -l $scratch/reconcile.py"
rec "cp test_reconcile.py README.md $scratch/ && cp -r samples_invalid expected_rewards.json recorded_payouts.json expected_report.json $scratch/ && ls $scratch"

# --- BEFORE: one record per documented condition, against the pre-fix source
rec "cd $scratch && python3 reconcile.py samples_invalid/valid_pair_expected.json samples_invalid/valid_pair_payouts.json > /dev/null"
rec "cd $scratch && python3 reconcile.py expected_rewards.json recorded_payouts.json > /dev/null"
rec "cd $scratch && python3 reconcile.py samples_invalid/amount_out_of_range.json samples_invalid/valid_pair_payouts.json 2>&1 | tail -1"
rec "cd $scratch && python3 reconcile.py samples_invalid/amount_infinity.json samples_invalid/valid_pair_payouts.json 2>&1 | tail -1"
rec "cd $scratch && python3 reconcile.py samples_invalid samples_invalid/valid_pair_payouts.json 2>&1 | tail -1"
rec "cd $scratch && python3 reconcile.py samples_invalid/not_utf8.json samples_invalid/valid_pair_payouts.json 2>&1 | tail -1"
rec "cd $scratch && python3 reconcile.py samples_invalid/valid_pair_expected.json samples_invalid/valid_pair_payouts.json -o /dev/null/x.json 2>&1 | tail -1"
rec "cd $scratch && python3 -m unittest test_reconcile 2>&1 | tail -1"

# --- AFTER: the same conditions against the fixed source
rec "python3 reconcile.py samples_invalid/valid_pair_expected.json samples_invalid/valid_pair_payouts.json > /dev/null"
rec "python3 reconcile.py expected_rewards.json recorded_payouts.json > /dev/null"
rec "python3 reconcile.py samples_invalid/not_json.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/not_an_array.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/float_amount.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/missing_field.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/duplicate_task_id.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/no_such_file.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/not_utf8.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/amount_out_of_range.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/amount_infinity.json samples_invalid/valid_pair_payouts.json"
rec "python3 reconcile.py samples_invalid/valid_pair_expected.json samples_invalid/valid_pair_payouts.json -o /dev/null/x.json"
rec "python3 reconcile.py expected_rewards.json recorded_payouts.json -o /dev/null/x.json"
rec "python3 reconcile.py samples_invalid/valid_pair_expected.json"
rec "python3 -m unittest test_reconcile.TestDocumentedExitCodes test_reconcile.TestRepairedExitCodes 2>&1 | tail -4"
rec "python3 -m unittest test_reconcile 2>&1 | tail -4"
# Two records, not one pipeline: under pipefail a pipe would report the
# reconciliation's own exit 1 and hide cmp's verdict.
rec "python3 reconcile.py expected_rewards.json recorded_payouts.json -o _cmp_report.json"
rec "cmp _cmp_report.json expected_report.json && echo REPORT_UNCHANGED_BY_THIS_FIX"
rm -f _cmp_report.json

rm -rf "$scratch"
rec "ls -d $scratch 2>&1; echo scratch-removed"
