#!/usr/bin/env python3
"""Tests for the two report/exit-code integrity defects in regress.py, and
for the fixtures/ generator that makes the committed CLI tests runnable.

Kept in its own file (same pattern as test_regress_newline.py) so the
original suite stays a readable record of the pre-fix contract.

Three groups:

  1. `expected_exit_code` must reject JSON booleans. `bool` subclasses
     `int` in Python, so `false` used to pass an `isinstance(x, int)`
     check and then compare equal to a real exit status of 0.

  2. A run that did not terminate normally must never be trusted, and
     must never be written into a baseline. `subprocess` reports a
     signalled process as a negative returncode; the old code compared
     that against `expected_exit_code` as if it were an exit status and
     hashed whatever partial bytes the dying process had left behind.

  3. `fixtures/` is generated by `make_fixtures.py` (repo convention:
     no generated tree is committed) and the generator is deterministic,
     so the tree is re-derived rather than trusted.

Stdlib only.
"""

import hashlib
import json
import os
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import regress  # noqa: E402
import make_fixtures  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REGRESS_PY = os.path.join(HERE, "regress.py")
MAKE_FIXTURES_PY = os.path.join(HERE, "make_fixtures.py")
FIXTURES_DIR = os.path.join(HERE, "fixtures")
PY = sys.executable or "python3"

POSIX_ONLY = unittest.skipUnless(os.name == "posix", "signal semantics are POSIX-specific")


def setUpModule():
    """`fixtures/` is generated, not committed -- the same convention as
    `bundle-verifier/`, `exit-harness/` and `tamper-runner/`, which all ship a
    `make_fixtures.py` and commit no generated tree. Build it on demand so the
    CLI-level tests below are runnable from a fresh clone."""
    if not os.path.isdir(FIXTURES_DIR):
        import make_fixtures
        make_fixtures.build(FIXTURES_DIR)



def run_cli(args, cwd=None):
    proc = subprocess.run(
        [PY, REGRESS_PY] + args,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=120,
    )
    return proc.returncode, proc.stdout.decode("utf-8"), proc.stderr.decode("utf-8")


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def read_json(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write_baselines(root, tools):
    path = os.path.join(root, "baselines.json")
    write(path, json.dumps({"tools": tools}))
    return path


# A tool that writes part of a report, flushes it to disk, then kills itself
# with SIGKILL. The report file therefore exists and is non-empty, but is
# truncated -- the exact shape the old code hashed and trusted.
PARTIAL_THEN_KILL = '''\
import os, signal, sys
out = sys.argv[sys.argv.index("-o") + 1]
fh = open(out, "w", encoding="utf-8", newline="\\n")
fh.write('{"tool":"crasher","partial":tr')
fh.flush()
os.fsync(fh.fileno())
os.kill(os.getpid(), signal.SIGKILL)
'''

# Creates the report file, writes nothing, exits 0.
EMPTY_REPORT = '''\
import sys
out = sys.argv[sys.argv.index("-o") + 1]
open(out, "w", encoding="utf-8").close()
sys.exit(0)
'''

GOOD_REPORT = '''\
import sys
out = sys.argv[sys.argv.index("-o") + 1]
with open(out, "w", encoding="utf-8", newline="\\n") as fh:
    fh.write('{"tool":"good"}\\n')
sys.exit(0)
'''


class TempRootMixin:
    def make_root(self):
        td = tempfile.TemporaryDirectory()
        self.addCleanup(td.cleanup)
        return td.name

    def make_tool(self, root, name, source):
        write(os.path.join(root, name, "tool.py"), source)
        return os.path.join(root, name)


# ---------------------------------------------------------------------------
# 1. Booleans are not exit codes
# ---------------------------------------------------------------------------

class TestIsExitCode(unittest.TestCase):
    def test_real_ints_accepted(self):
        for value in (0, 1, 2, 127, -1, 255):
            self.assertTrue(regress.is_exit_code(value), value)

    def test_booleans_rejected(self):
        self.assertFalse(regress.is_exit_code(True))
        self.assertFalse(regress.is_exit_code(False))

    def test_non_ints_rejected(self):
        for value in ("0", 0.0, None, [], {}, object()):
            self.assertFalse(regress.is_exit_code(value), repr(value))

    def test_bool_would_have_compared_equal_to_zero(self):
        # The reason the bug was silent rather than loud.
        self.assertTrue(0 == False)  # noqa: E712
        self.assertTrue(1 == True)  # noqa: E712
        self.assertTrue(isinstance(False, int))


class TestBooleanExitCodeRejected(TempRootMixin, unittest.TestCase):
    def entry(self, exit_code):
        return {"command": ["python3", "tool.py"], "report_mode": "stdout",
                "expected_exit_code": exit_code}

    def test_false_rejected_by_load_baselines(self):
        path = write_baselines(self.make_root(), {"t1": self.entry(False)})
        with self.assertRaises(regress.SetupError):
            regress.load_baselines(path)

    def test_true_rejected_by_load_baselines(self):
        path = write_baselines(self.make_root(), {"t1": self.entry(True)})
        with self.assertRaises(regress.SetupError):
            regress.load_baselines(path)

    def test_zero_still_accepted(self):
        path = write_baselines(self.make_root(), {"t1": self.entry(0)})
        self.assertEqual(regress.load_baselines(path)["t1"]["expected_exit_code"], 0)

    def test_error_message_names_the_boolean(self):
        path = write_baselines(self.make_root(), {"t1": self.entry(False)})
        with self.assertRaises(regress.SetupError) as ctx:
            regress.load_baselines(path)
        self.assertIn("boolean", str(ctx.exception).lower())
        self.assertIn("t1", str(ctx.exception))

    def test_cli_exits_two_and_reports_error(self):
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        path = write_baselines(root, {"t1": self.entry(False)})
        code, out, _ = run_cli(["--root", root, "--baselines", path])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_a_tool_exiting_zero_no_longer_matches_false(self):
        # End-to-end statement of the defect: before the fix this baseline
        # was accepted and the tool was reported clean against `false`.
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        path = write_baselines(root, {"t1": {
            "command": ["python3", "tool.py", "-o", "{REPORT}"],
            "report_mode": "file",
            "expected_exit_code": False,
            "expected_report_sha256": None,
        }})
        code, out, _ = run_cli(["--root", root, "--baselines", path])
        self.assertEqual(code, 2, msg=out)

    def test_update_baselines_refuses_boolean_entry(self):
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        path = write_baselines(root, {"t1": {
            "command": ["python3", "tool.py", "-o", "{REPORT}"],
            "report_mode": "file",
            "expected_exit_code": False,
            "expected_report_sha256": None,
        }})
        code, _, err = run_cli(["--update-baselines", "--root", root, "--baselines", path])
        self.assertEqual(code, 2)
        self.assertIn("FAILED", err)
        # and the boolean was not quietly rewritten into a 0
        self.assertIs(read_json(path)["tools"]["t1"]["expected_exit_code"], False)


# ---------------------------------------------------------------------------
# 2. A crashed run is not a result
# ---------------------------------------------------------------------------

class TestTerminationRecorded(TempRootMixin, unittest.TestCase):
    def file_entry(self, exit_code=0, digest=None):
        return {
            "status": "baselined",
            "command": ["python3", "tool.py", "-o", "{REPORT}"],
            "report_mode": "file",
            "expected_exit_code": exit_code,
            "expected_report_sha256": digest,
        }

    def test_normal_run_reports_exited(self):
        root = self.make_root()
        d = self.make_tool(root, "t1", GOOD_REPORT)
        result = regress.run_tool(d, self.file_entry(), timeout=60)
        self.assertTrue(result["ok"])
        self.assertEqual(result["termination"], regress.TERM_EXITED)
        self.assertIsNone(result["signal"])

    @POSIX_ONLY
    def test_signalled_run_reports_signalled_and_signal_number(self):
        root = self.make_root()
        d = self.make_tool(root, "t1", PARTIAL_THEN_KILL)
        result = regress.run_tool(d, self.file_entry(), timeout=60)
        self.assertEqual(result["termination"], regress.TERM_SIGNALLED)
        self.assertEqual(result["signal"], 9)

    @POSIX_ONLY
    def test_partial_report_is_still_read_but_flagged(self):
        # The bytes are readable -- that was never the problem. The problem
        # was that nothing recorded HOW the process ended.
        root = self.make_root()
        d = self.make_tool(root, "t1", PARTIAL_THEN_KILL)
        result = regress.run_tool(d, self.file_entry(), timeout=60)
        self.assertTrue(result["ok"])
        self.assertGreater(result["report_bytes_length"], 0)
        self.assertEqual(result["termination"], regress.TERM_SIGNALLED)


class TestAbnormalTerminationDrift(TempRootMixin, unittest.TestCase):
    def run_report(self, root, baselines):
        path = write_baselines(root, baselines)
        code, out, err = run_cli(["--root", root, "--baselines", path])
        return code, json.loads(out), err

    def entry(self, exit_code, digest):
        return {
            "command": ["python3", "tool.py", "-o", "{REPORT}"],
            "report_mode": "file",
            "expected_exit_code": exit_code,
            "expected_report_sha256": digest,
        }

    @POSIX_ONLY
    def test_signalled_run_raises_abnormal_termination(self):
        root = self.make_root()
        self.make_tool(root, "crasher", PARTIAL_THEN_KILL)
        digest = hashlib.sha256(b'{"tool":"crasher","partial":tr').hexdigest()
        code, report, _ = self.run_report(root, {"crasher": self.entry(-9, digest)})
        result = report["results"][0]
        self.assertIn(regress.DRIFT_ABNORMAL, result["drift_codes"])
        self.assertEqual(code, 1)

    @POSIX_ONLY
    def test_baseline_recording_negative_code_cannot_bless_a_crash(self):
        # The whole point: a baseline that says "-9 is expected" must not
        # make a SIGKILLed run come out clean.
        root = self.make_root()
        self.make_tool(root, "crasher", PARTIAL_THEN_KILL)
        digest = hashlib.sha256(b'{"tool":"crasher","partial":tr').hexdigest()
        _, report, _ = self.run_report(root, {"crasher": self.entry(-9, digest)})
        self.assertEqual(report["results"][0]["status"], "drift")

    @POSIX_ONLY
    def test_detail_carries_termination_and_signal(self):
        root = self.make_root()
        self.make_tool(root, "crasher", PARTIAL_THEN_KILL)
        _, report, _ = self.run_report(root, {"crasher": self.entry(0, None)})
        detail = report["results"][0]["detail"]
        self.assertEqual(detail["termination"], regress.TERM_SIGNALLED)
        self.assertEqual(detail["signal"], 9)

    def test_clean_run_detail_says_exited(self):
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        digest = hashlib.sha256(b'{"tool":"good"}\n').hexdigest()
        code, report, _ = self.run_report(root, {"t1": self.entry(0, digest)})
        self.assertEqual(code, 0)
        self.assertEqual(report["results"][0]["detail"]["termination"], regress.TERM_EXITED)
        self.assertNotIn("signal", report["results"][0]["detail"])

    def test_abnormal_code_is_in_all_drift_codes(self):
        self.assertIn(regress.DRIFT_ABNORMAL, regress.ALL_DRIFT_CODES)

    def test_drift_counts_include_abnormal_key(self):
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        digest = hashlib.sha256(b'{"tool":"good"}\n').hexdigest()
        _, report, _ = self.run_report(root, {"t1": self.entry(0, digest)})
        self.assertIn(regress.DRIFT_ABNORMAL, report["drift_counts"])

    def test_schema_version_bumped(self):
        self.assertEqual(regress.SCHEMA_VERSION, 2)


class TestUpdateBaselinesRefusesBadRuns(TempRootMixin, unittest.TestCase):
    def entry(self):
        return {
            "command": ["python3", "tool.py", "-o", "{REPORT}"],
            "report_mode": "file",
            "expected_exit_code": 0,
            "expected_report_sha256": "0" * 64,
        }

    @POSIX_ONLY
    def test_refuses_to_baseline_a_signalled_run(self):
        root = self.make_root()
        self.make_tool(root, "crasher", PARTIAL_THEN_KILL)
        path = write_baselines(root, {"crasher": self.entry()})
        before = read_text(path)
        code, _, err = run_cli(["--update-baselines", "--root", root, "--baselines", path])
        self.assertEqual(code, 2)
        self.assertIn("signal", err)
        self.assertEqual(json.loads(before)["tools"]["crasher"]["expected_report_sha256"],
                         read_json(path)["tools"]["crasher"]["expected_report_sha256"])

    def test_refuses_to_baseline_an_empty_report(self):
        root = self.make_root()
        self.make_tool(root, "empty", EMPTY_REPORT)
        path = write_baselines(root, {"empty": self.entry()})
        code, _, err = run_cli(["--update-baselines", "--root", root, "--baselines", path])
        self.assertEqual(code, 2)
        self.assertIn("0-byte", err)
        self.assertEqual(read_json(path)["tools"]["empty"]["expected_report_sha256"], "0" * 64)

    def test_allow_empty_report_opts_back_in(self):
        root = self.make_root()
        self.make_tool(root, "empty", EMPTY_REPORT)
        path = write_baselines(root, {"empty": self.entry()})
        code, _, err = run_cli(["--update-baselines", "--allow-empty-report",
                                "--root", root, "--baselines", path])
        self.assertEqual(code, 0, msg=err)
        self.assertEqual(read_json(path)["tools"]["empty"]["expected_report_sha256"],
                         hashlib.sha256(b"").hexdigest())

    def test_healthy_run_still_updates(self):
        root = self.make_root()
        self.make_tool(root, "t1", GOOD_REPORT)
        path = write_baselines(root, {"t1": self.entry()})
        code, _, err = run_cli(["--update-baselines", "--root", root, "--baselines", path])
        self.assertEqual(code, 0, msg=err)
        self.assertEqual(read_json(path)["tools"]["t1"]["expected_report_sha256"],
                         hashlib.sha256(b'{"tool":"good"}\n').hexdigest())

    def test_empty_sha256_constant_matches_hashlib(self):
        self.assertEqual(regress.EMPTY_SHA256, hashlib.sha256(b"").hexdigest())


# ---------------------------------------------------------------------------
# 3. fixtures/ is generated, and the generator is deterministic
# ---------------------------------------------------------------------------

class TestFixtureGenerator(unittest.TestCase):
    def test_on_disk_fixtures_match_the_generator(self):
        proc = subprocess.run([PY, MAKE_FIXTURES_PY, "--check"], cwd=HERE,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120)
        self.assertEqual(proc.returncode, 0, msg=proc.stdout.decode() + proc.stderr.decode())

    def test_generator_is_deterministic_across_two_runs(self):
        with tempfile.TemporaryDirectory() as td:
            a, b = os.path.join(td, "a"), os.path.join(td, "b")
            make_fixtures.build(a)
            make_fixtures.build(b)
            self.assertEqual(make_fixtures.snapshot(a), make_fixtures.snapshot(b))

    def test_generated_tree_has_the_seven_documented_tool_dirs(self):
        with tempfile.TemporaryDirectory() as td:
            out = os.path.join(td, "fixtures")
            make_fixtures.build(out)
            dirs = sorted(d for d in os.listdir(out) if os.path.isdir(os.path.join(out, d)))
        self.assertEqual(dirs, sorted(make_fixtures.FIXTURE_TOOLS))
        self.assertEqual(len(dirs), 7)

    def test_tool_error_has_no_tool_py(self):
        self.assertFalse(os.path.exists(os.path.join(FIXTURES_DIR, "tool_error", "tool.py")))

    def test_ok_baseline_has_exactly_two_unbaselineable(self):
        data = read_json(os.path.join(FIXTURES_DIR, "baselines_ok.json"))
        n = sum(1 for e in data["tools"].values() if e.get("status") == "unbaselineable")
        self.assertEqual(n, 2)

    def test_drift_baseline_names_ghost_tool_with_no_directory(self):
        data = read_json(os.path.join(FIXTURES_DIR, "baselines_drift.json"))
        self.assertIn("ghost_tool", data["tools"])
        self.assertFalse(os.path.exists(os.path.join(FIXTURES_DIR, "ghost_tool")))

    def test_no_absolute_interpreter_path_in_generated_baselines(self):
        # An absolute sys.executable baked into a baseline file is
        # unreproducible on any other machine.
        for name in ("baselines_ok.json", "baselines_drift.json"):
            text = read_text(os.path.join(FIXTURES_DIR, name))
            self.assertNotIn("/usr/", text, name)
            self.assertNotIn("/home", text, name)
            self.assertNotIn(HERE, text, name)

    def test_no_boolean_exit_codes_in_generated_baselines(self):
        for name in ("baselines_ok.json", "baselines_drift.json"):
            data = read_json(os.path.join(FIXTURES_DIR, name))
            for tool, entry in data["tools"].items():
                if entry.get("status") == "unbaselineable":
                    continue
                self.assertTrue(regress.is_exit_code(entry["expected_exit_code"]),
                                "%s/%s" % (name, tool))

    def test_shell_meta_token_survives_verbatim(self):
        # Proof that regress.py never routes a command through a shell.
        code, out, err = run_cli(
            ["--root", "fixtures", "--baselines", "fixtures/baselines_ok.json"], cwd=HERE)
        self.assertEqual(code, 0, msg=err)
        report = json.loads(out)
        by_name = {r["tool"]: r for r in report["results"]}
        self.assertEqual(by_name["tool_shell_meta"]["status"], "clean")


if __name__ == "__main__":
    unittest.main()
