#!/usr/bin/env python3
"""Recreate fixture_tools/ byte-for-byte.

Contents are stored base64-encoded and written in BINARY mode on purpose, so a
text-mode round trip cannot silently rewrite line endings and invalidate the
committed sample report hashes.

EMPTY_DIRS is not decoration. Four case directories are deliberately empty --
they exist only to give a case a working directory in which the tool under test
finds no input. os.walk yields no files for them, so an earlier version of this
generator dropped them and the regenerated tree produced a DIFFERENT report
hash. Empty directories are part of the fixture.

Regenerating and re-running reproduces the committed sample reports
byte-for-byte; captured_output.txt shows that round trip.

    python3 make_fixtures.py [dest]
"""
import base64
import os
import sys

EMPTY_DIRS = [
 "fixture_tools/cases/linecount_misuse",
 "fixture_tools/cases/sleeper_findings",
 "fixture_tools/cases/sleeper_misuse",
 "fixture_tools/cases/sleeper_ok"
]

FILES = {
 "fixture_tools/cases/linecount_empty/blank.txt": "ICAgCgogIAo=",
 "fixture_tools/cases/linecount_ok/notes.txt": "Zmlyc3QgbGluZSBoYXMgd29yZHMKc2Vjb25kIGxpbmUgdG9vCg==",
 "fixture_tools/cases/validate_findings/bad.json": "eyJuYW1lIjogIiIsICJhZ2UiOiAtMX0K",
 "fixture_tools/cases/validate_misuse/not_json.txt": "dGhpcyBpcyBub3QganNvbiBhdCBhbGwge3t7Cg==",
 "fixture_tools/cases/validate_ok/good.json": "eyJuYW1lIjogIkFkYSBMb3ZlbGFjZSIsICJhZ2UiOiAzNn0K",
 "fixture_tools/linecount.py": "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiJsaW5lY291bnQucHkgLS0gZXhhbXBsZSBmaXh0dXJlIHRvb2wgIzIgZm9yIGV4aXQtaGFybmVzcy4KCkEgdGlueSBzdGRsaWItb25seSBsaW5lL3dvcmQgY291bnRlci4gUmVhZHMgYSB0ZXh0IGZpbGUgZ2l2ZW4gYXMgaXRzCnNpbmdsZSBhcmd1bWVudCBhbmQgcmVwb3J0cyBjb3VudHMgYXMgY2Fub25pY2FsIEpTT04gb24gc3Rkb3V0LgoKRXhpdCBjb2RlczoKICAwIC0gZmlsZSBleGlzdHMsIGlzIHJlYWRhYmxlLCBhbmQgaGFzIGF0IGxlYXN0IG9uZSBub24tYmxhbmsgbGluZTsKICAgICAgcHJpbnRzIGNhbm9uaWNhbCBKU09OIHsibGluZXMiOk4sIndvcmRzIjpOfSB0byBzdGRvdXQuCiAgMSAtIGZpbGUgZXhpc3RzIGFuZCBpcyByZWFkYWJsZSBidXQgY29udGFpbnMgemVybyBub24tYmxhbmsgbGluZXMKICAgICAgKGEgImZpbmRpbmciOiBub3RoaW5nIHRvIGNvdW50KS4gUHJpbnRzIGEgbWVzc2FnZSB0byBzdGRvdXQKICAgICAgKHBsYWluIHRleHQsIG9uIHB1cnBvc2UsIHNvIGl0IGFsc28gc2VydmVzIGFzIGEKICAgICAgU1RET1VUX05PVF9KU09OIC8gc3Vic3RyaW5nLWNoZWNrIGV4YW1wbGUpIGFuZCBleGl0cyAxLgogIDIgLSBtaXN1c2U6IHdyb25nIG51bWJlciBvZiBhcmd1bWVudHMgb3IgdGhlIGZpbGUgY2Fubm90IGJlIG9wZW5lZC4KIiIiCmltcG9ydCBqc29uCmltcG9ydCBzeXMKCgpkZWYgbWFpbihhcmd2KToKICAgIGlmIGxlbihhcmd2KSAhPSAyOgogICAgICAgIHByaW50KCJ1c2FnZTogbGluZWNvdW50LnB5IDxmaWxlLnR4dD4iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDIKCiAgICBwYXRoID0gYXJndlsxXQogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihwYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIHRleHQgPSBmLnJlYWQoKQogICAgZXhjZXB0IE9TRXJyb3IgYXMgZXhjOgogICAgICAgIHByaW50KGYiZXJyb3I6IGNhbm5vdCByZWFkIGZpbGU6IHtleGMuc3RyZXJyb3J9IiwgZmlsZT1zeXMuc3RkZXJyKQogICAgICAgIHJldHVybiAyCgogICAgbGluZXMgPSBbbG4gZm9yIGxuIGluIHRleHQuc3BsaXRsaW5lcygpIGlmIGxuLnN0cmlwKCkgIT0gIiJdCiAgICBpZiBub3QgbGluZXM6CiAgICAgICAgcHJpbnQoImVtcHR5OiBubyBub24tYmxhbmsgbGluZXMgZm91bmQiKQogICAgICAgIHJldHVybiAxCgogICAgd29yZHMgPSBzdW0obGVuKGxuLnNwbGl0KCkpIGZvciBsbiBpbiBsaW5lcykKICAgIHN5cy5zdGRvdXQud3JpdGUoCiAgICAgICAganNvbi5kdW1wcyh7ImxpbmVzIjogbGVuKGxpbmVzKSwgIndvcmRzIjogd29yZHN9LCBzb3J0X2tleXM9VHJ1ZSwgc2VwYXJhdG9ycz0oIiwiLCAiOiIpLCBlbnN1cmVfYXNjaWk9VHJ1ZSkKICAgICAgICArICJcbiIKICAgICkKICAgIHJldHVybiAwCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN5cy5leGl0KG1haW4oc3lzLmFyZ3YpKQo=",
 "fixture_tools/sleeper.py": "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiJzbGVlcGVyLnB5IC0tIGV4YW1wbGUgZml4dHVyZSB0b29sICMzIGZvciBleGl0LWhhcm5lc3MuCgpBIHRpbnkgc3RkbGliLW9ubHkgdG9vbCB0aGF0IHNsZWVwcyBmb3IgYSBjb25maWd1cmFibGUgZHVyYXRpb24gYW5kIHRoZW4KZXhpdHMgd2l0aCBhIGNvbmZpZ3VyYWJsZSBjb2RlLiBVc2VkIHRvIGRlbW9uc3RyYXRlIG9yZGluYXJ5IDAvMS8yIGV4aXQKYmVoYXZpb3VyICphbmQqIHRvIGdpdmUgZXhpdC1oYXJuZXNzJ3Mgb3duIHRlc3Qgc3VpdGUgYSBkZWxpYmVyYXRlbHkgc2xvdwpjYXNlIGZvciBleGVyY2lzaW5nIFRJTUVPVVQgaGFuZGxpbmcuCgpVc2FnZTogc2xlZXBlci5weSA8c2Vjb25kcz4gW2V4aXRfY29kZV0KCkV4aXQgY29kZXM6CiAgMCAtIGRlZmF1bHQ7IHNsZWVwcyB0aGVuIHByaW50cyBjYW5vbmljYWwgSlNPTiB7InNsZXB0Ijo8c2Vjb25kcz59IGFuZAogICAgICBleGl0cyAwLgogIDEgLSBpZiBleGl0X2NvZGUgYXJndW1lbnQgaXMgIjEiLCBzbGVlcHMgdGhlbiBwcmludHMgYSBmaW5kaW5nIGxpbmUgdG8KICAgICAgc3Rkb3V0IGFuZCBleGl0cyAxLgogIDIgLSBtaXN1c2U6IHdyb25nIG51bWJlciBvZiBhcmd1bWVudHMsIDxzZWNvbmRzPiBub3QgYSB2YWxpZAogICAgICBub24tbmVnYXRpdmUgbnVtYmVyLCBvciBleGl0X2NvZGUgYXJndW1lbnQgaXMgbmVpdGhlciAiMCIgbm9yICIxIi4KIiIiCmltcG9ydCBqc29uCmltcG9ydCBzeXMKaW1wb3J0IHRpbWUKCgpkZWYgbWFpbihhcmd2KToKICAgIGlmIGxlbihhcmd2KSBub3QgaW4gKDIsIDMpOgogICAgICAgIHByaW50KCJ1c2FnZTogc2xlZXBlci5weSA8c2Vjb25kcz4gW2V4aXRfY29kZV0iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDIKCiAgICB0cnk6CiAgICAgICAgc2Vjb25kcyA9IGZsb2F0KGFyZ3ZbMV0pCiAgICAgICAgaWYgc2Vjb25kcyA8IDA6CiAgICAgICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIm5lZ2F0aXZlIikKICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgIHByaW50KCJlcnJvcjogPHNlY29uZHM+IG11c3QgYmUgYSBub24tbmVnYXRpdmUgbnVtYmVyIiwgZmlsZT1zeXMuc3RkZXJyKQogICAgICAgIHJldHVybiAyCgogICAgZXhpdF9jb2RlID0gYXJndlsyXSBpZiBsZW4oYXJndikgPT0gMyBlbHNlICIwIgogICAgaWYgZXhpdF9jb2RlIG5vdCBpbiAoIjAiLCAiMSIpOgogICAgICAgIHByaW50KCJlcnJvcjogZXhpdF9jb2RlIG11c3QgYmUgJzAnIG9yICcxJyIsIGZpbGU9c3lzLnN0ZGVycikKICAgICAgICByZXR1cm4gMgoKICAgIHRpbWUuc2xlZXAoc2Vjb25kcykKCiAgICBpZiBleGl0X2NvZGUgPT0gIjEiOgogICAgICAgIHByaW50KCJGSU5ESU5HOiBzbGVwdCBsb25nZXIgdGhhbiBleHBlY3RlZCBieSBjYWxsZXIiKQogICAgICAgIHJldHVybiAxCgogICAgc3lzLnN0ZG91dC53cml0ZShqc29uLmR1bXBzKHsic2xlcHQiOiBzZWNvbmRzfSwgc29ydF9rZXlzPVRydWUsIHNlcGFyYXRvcnM9KCIsIiwgIjoiKSwgZW5zdXJlX2FzY2lpPVRydWUpICsgIlxuIikKICAgIHJldHVybiAwCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN5cy5leGl0KG1haW4oc3lzLmFyZ3YpKQo=",
 "fixture_tools/validator.py": "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiJ2YWxpZGF0b3IucHkgLS0gZXhhbXBsZSBmaXh0dXJlIHRvb2wgIzEgZm9yIGV4aXQtaGFybmVzcy4KCkEgdGlueSBzdGRsaWItb25seSAicmVjb3JkIHZhbGlkYXRvciIuIEl0IHJlYWRzIGEgSlNPTiBmaWxlIGdpdmVuIGFzIGl0cwpzaW5nbGUgYXJndW1lbnQsIGNoZWNrcyB0aGF0IGl0IGlzIGEgSlNPTiBvYmplY3Qgd2l0aCBhIG5vbi1lbXB0eSBzdHJpbmcKIm5hbWUiIGZpZWxkIGFuZCBhbiBpbnRlZ2VyICJhZ2UiIGZpZWxkID49IDAsIGFuZCByZXBvcnRzIHRoZSBvdXRjb21lLgoKRXhpdCBjb2RlcyAodGhlIGNvbnRyYWN0IGV4aXQtaGFybmVzcyBjaGVja3MpOgogIDAgLSBpbnB1dCBwYXJzZXMgYW5kIGlzIGZ1bGx5IHZhbGlkOyBwcmludHMgYSBjYW5vbmljYWwgSlNPTiBvYmplY3QKICAgICAgeyJzdGF0dXMiOiJvayJ9IHRvIHN0ZG91dC4KICAxIC0gaW5wdXQgcGFyc2VzIGFzIEpTT04gYnV0IGhhcyB2YWxpZGF0aW9uIGZpbmRpbmdzOyBlYWNoIGZpbmRpbmcgaXMKICAgICAgcHJpbnRlZCBvbiBpdHMgb3duIGxpbmUgdG8gc3Rkb3V0ICh0aGlzIGlzIGRlbGliZXJhdGVseSBOT1QgSlNPTiwKICAgICAgdG8gZXhlcmNpc2UgdGhlICJub3QgY2Fub25pY2FsIiAvIHBsYWluIHN1YnN0cmluZyBjaGVja3MpIGFuZCBhCiAgICAgIHNob3J0IHN1bW1hcnkgaXMgcHJpbnRlZCB0byBzdGRlcnIuCiAgMiAtIG1pc3VzZTogd3JvbmcgbnVtYmVyIG9mIGFyZ3VtZW50cywgZmlsZSBkb2VzIG5vdCBleGlzdCwgb3IgZmlsZQogICAgICBjb250ZW50IGlzIG5vdCB2YWxpZCBKU09OIGF0IGFsbC4gQSBtZXNzYWdlIGlzIHByaW50ZWQgdG8gc3RkZXJyLgoiIiIKaW1wb3J0IGpzb24KaW1wb3J0IHN5cwoKCmRlZiBtYWluKGFyZ3YpOgogICAgaWYgbGVuKGFyZ3YpICE9IDI6CiAgICAgICAgcHJpbnQoInVzYWdlOiB2YWxpZGF0b3IucHkgPGZpbGUuanNvbj4iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDIKCiAgICBwYXRoID0gYXJndlsxXQogICAgdHJ5OgogICAgICAgIHdpdGggb3BlbihwYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIHJhdyA9IGYucmVhZCgpCiAgICBleGNlcHQgT1NFcnJvciBhcyBleGM6CiAgICAgICAgcHJpbnQoZiJlcnJvcjogY2Fubm90IHJlYWQgZmlsZToge2V4Yy5zdHJlcnJvcn0iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDIKCiAgICB0cnk6CiAgICAgICAgZGF0YSA9IGpzb24ubG9hZHMocmF3KQogICAgZXhjZXB0IGpzb24uSlNPTkRlY29kZUVycm9yIGFzIGV4YzoKICAgICAgICBwcmludChmImVycm9yOiBub3QgdmFsaWQgSlNPTjoge2V4Y30iLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDIKCiAgICBmaW5kaW5ncyA9IFtdCiAgICBpZiBub3QgaXNpbnN0YW5jZShkYXRhLCBkaWN0KToKICAgICAgICBmaW5kaW5ncy5hcHBlbmQoInJvb3QgdmFsdWUgbXVzdCBiZSBhIEpTT04gb2JqZWN0IikKICAgIGVsc2U6CiAgICAgICAgbmFtZSA9IGRhdGEuZ2V0KCJuYW1lIikKICAgICAgICBpZiBub3QgaXNpbnN0YW5jZShuYW1lLCBzdHIpIG9yIG5vdCBuYW1lOgogICAgICAgICAgICBmaW5kaW5ncy5hcHBlbmQoImZpZWxkICduYW1lJyBtdXN0IGJlIGEgbm9uLWVtcHR5IHN0cmluZyIpCiAgICAgICAgYWdlID0gZGF0YS5nZXQoImFnZSIpCiAgICAgICAgaWYgbm90IGlzaW5zdGFuY2UoYWdlLCBpbnQpIG9yIGlzaW5zdGFuY2UoYWdlLCBib29sKSBvciBhZ2UgPCAwOgogICAgICAgICAgICBmaW5kaW5ncy5hcHBlbmQoImZpZWxkICdhZ2UnIG11c3QgYmUgYSBub24tbmVnYXRpdmUgaW50ZWdlciIpCgogICAgaWYgZmluZGluZ3M6CiAgICAgICAgZm9yIGZpbmRpbmcgaW4gZmluZGluZ3M6CiAgICAgICAgICAgIHByaW50KGYiRklORElORzoge2ZpbmRpbmd9IikKICAgICAgICBwcmludChmInZhbGlkYXRpb24gZmFpbGVkIHdpdGgge2xlbihmaW5kaW5ncyl9IGZpbmRpbmcocykiLCBmaWxlPXN5cy5zdGRlcnIpCiAgICAgICAgcmV0dXJuIDEKCiAgICBzeXMuc3Rkb3V0LndyaXRlKGpzb24uZHVtcHMoeyJzdGF0dXMiOiAib2sifSwgc29ydF9rZXlzPVRydWUsIHNlcGFyYXRvcnM9KCIsIiwgIjoiKSwgZW5zdXJlX2FzY2lpPVRydWUpICsgIlxuIikKICAgIHJldHVybiAwCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN5cy5leGl0KG1haW4oc3lzLmFyZ3YpKQo="
}


def main():
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    for rel in sorted(EMPTY_DIRS):
        os.makedirs(os.path.join(dest, *rel.split("/")), exist_ok=True)
    for rel in sorted(FILES):
        path = os.path.join(dest, *rel.split("/"))
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(path, "wb") as fh:
            fh.write(base64.b64decode(FILES[rel]))
    print("wrote %d files and %d empty dirs to %s"
          % (len(FILES), len(EMPTY_DIRS), dest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
