#!/usr/bin/env python3
"""make_fixtures.py -- write the NUL-delimited fixture path lists.

The fixtures this tool needs are *path names*, and several of them cannot
exist as real files on the machine that has to produce them: a name
containing a newline is illegal on Windows, `aux.json` cannot be created
there at all, and a name that differs from another only by case cannot
coexist on macOS. So the fixtures are path *lists* -- NUL-delimited
bytes -- not directory trees. That is also why `pathscan.py` has a
`--paths-from` mode at all.

The lists are written as raw bytes rather than committed as text files
because a NUL-delimited file does not survive an editor, a diff viewer,
or a web upload form intact.

Usage:
    python3 make_fixtures.py [--out fixtures]
    python3 make_fixtures.py --check      # verify, write nothing

Exit codes: 0 success / --check passed, 1 --check mismatch, 2 setup error.
"""

import argparse
import hashlib
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))

# Every path here is deliberate. Comments name the rule each one triggers.
CLEAN_PATHS = [
    "README.md",
    "src/main.py",
    "src/util/helpers.py",
    "docs/guide.md",
    "tests/test_main.py",
]

DIRTY_PATHS = [
    # clean controls -- must produce no finding at all
    "README.md",
    "src/main.py",
    # CASE_FOLD_COLLISION: differ only by case
    "docs/Guide.md",
    "docs/guide.md",
    # CASE_FOLD_COLLISION on a directory component, not the file name
    "Src/other.py",
    "src/other.py",
    # UNICODE_NORMALIZATION_COLLISION: NFC vs NFD of "café.txt"
    "notes/caf\u00e9.txt",
    "notes/cafe\u0301.txt",
    # WINDOWS_RESERVED_NAME: bare, with extension, and nested
    "aux",
    "data/NUL.json",
    "com1.txt",
    # TRAILING_DOT_OR_SPACE
    "reports/summary.",
    "reports/draft /notes.md",
    # CONTROL_CHARACTER: a real newline inside a file name
    "weird/two\nlines.txt",
    "weird/tab\there.txt",
    # WINDOWS_ILLEGAL_CHARACTER
    "out/report:v2.json",
    "out/what?.md",
    # UNSAFE_RELATIVE_PATH
    "../escape.txt",
    "/absolute/path.txt",
    "C:/drive/path.txt",
    "back\\slash.txt",
    "trailing/slash/",
    "double//sep.txt",
    "./dot.txt",
]

# Same list, with one entry repeated, for DUPLICATE_PATH.
DUP_PATHS = ["README.md", "src/main.py", "README.md", "src/main.py", "README.md"]

FIXTURES = {
    "clean.paths": CLEAN_PATHS,
    "dirty.paths": DIRTY_PATHS,
    "duplicates.paths": DUP_PATHS,
    "empty.paths": [],
}


def encode(paths):
    """NUL-delimited, with a trailing NUL after the last entry, like
    `git ls-files -z`. An empty list encodes to zero bytes."""
    if not paths:
        return b""
    return b"\0".join(p.encode("utf-8") for p in paths) + b"\0"


def build(out_dir):
    os.makedirs(out_dir, exist_ok=True)
    for name, paths in sorted(FIXTURES.items()):
        with open(os.path.join(out_dir, name), "wb") as fh:
            fh.write(encode(paths))
    # A deliberately malformed list: an interior empty entry (stray NUL).
    with open(os.path.join(out_dir, "malformed.paths"), "wb") as fh:
        fh.write(b"a.txt\0\0b.txt\0")
    # Invalid UTF-8, to exercise the decode failure path.
    with open(os.path.join(out_dir, "not_utf8.paths"), "wb") as fh:
        fh.write(b"ok.txt\0\xff\xfe\xfd\0")
    with open(os.path.join(out_dir, "README.txt"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "Generated by ../make_fixtures.py. Do not hand-edit: these are\n"
            "NUL-delimited byte streams, not text files.\n\n"
            "  clean.paths       no findings\n"
            "  dirty.paths       at least one of every rule except DUPLICATE_PATH\n"
            "  duplicates.paths  DUPLICATE_PATH only\n"
            "  empty.paths       zero bytes, zero paths\n"
            "  malformed.paths   interior empty entry -> setup error\n"
            "  not_utf8.paths    invalid UTF-8 entry -> setup error\n"
        )


def snapshot(root):
    out = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d != "__pycache__")
        for fn in sorted(filenames):
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            with open(full, "rb") as fh:
                out[rel] = hashlib.sha256(fh.read()).hexdigest()
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(prog="make_fixtures.py")
    ap.add_argument("--out", default=os.path.join(HERE, "fixtures"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    if not args.check:
        build(args.out)
        print("wrote %d files under %s" % (len(snapshot(args.out)), args.out))
        return 0

    if not os.path.isdir(args.out):
        sys.stderr.write("--check: %s does not exist\n" % args.out)
        return 1
    with tempfile.TemporaryDirectory(prefix="pcs_check_") as td:
        ref = os.path.join(td, "fixtures")
        build(ref)
        want, got = snapshot(ref), snapshot(args.out)
    if want == got:
        print("fixtures match the generator (%d files)" % len(want))
        return 0
    for rel in sorted(set(want) | set(got)):
        if want.get(rel) != got.get(rel):
            print("MISMATCH %s" % rel)
    return 1


if __name__ == "__main__":
    sys.exit(main())
