#!/usr/bin/env python3
"""Test suite for pathscan.py. Stdlib-only (unittest, tempfile, subprocess,
json, os, sys, hashlib).

Every scenario is a path *list*, never a directory tree, because several of
the names under test cannot exist as files on the machine running the
tests -- that is the whole point of the tool. The `fixtures/` tree is
generated by make_fixtures.py and built on demand by setUpModule().
"""

import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pathscan  # noqa: E402
import make_fixtures  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
PATHSCAN_PY = os.path.join(HERE, "pathscan.py")
MAKE_FIXTURES_PY = os.path.join(HERE, "make_fixtures.py")
FIXTURES_DIR = os.path.join(HERE, "fixtures")
PY = sys.executable or "python3"

HAVE_GIT = shutil.which("git") is not None
NEEDS_GIT = unittest.skipUnless(HAVE_GIT, "git is not on PATH")


def setUpModule():
    """fixtures/ is generated, not committed (repo convention)."""
    if not os.path.isdir(FIXTURES_DIR):
        make_fixtures.build(FIXTURES_DIR)


def run_cli(args, cwd=None, stdin_bytes=None):
    proc = subprocess.run(
        [PY, PATHSCAN_PY] + args,
        cwd=cwd,
        input=stdin_bytes,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=120,
    )
    return proc.returncode, proc.stdout.decode("utf-8"), proc.stderr.decode("utf-8")


def write_list(dirpath, name, paths, trailing_nul=True):
    data = b"\0".join(p.encode("utf-8") for p in paths)
    if paths and trailing_nul:
        data += b"\0"
    full = os.path.join(dirpath, name)
    with open(full, "wb") as fh:
        fh.write(data)
    return full


def scan_paths(paths):
    """Run the scanner in-process over a list and return the report dict."""
    return pathscan.build_report(paths, "path-list", set(pathscan.ALL_RULES))


def rules_fired(paths):
    return sorted({f["rule_id"] for f in scan_paths(paths)["findings"]})


class TempMixin:
    def tmp(self):
        td = tempfile.TemporaryDirectory()
        self.addCleanup(td.cleanup)
        return td.name


# ---------------------------------------------------------------------------
# canonical_json
# ---------------------------------------------------------------------------

class TestCanonicalJson(unittest.TestCase):
    def test_single_trailing_newline(self):
        out = pathscan.canonical_json({"a": 1})
        self.assertTrue(out.endswith("\n"))
        self.assertFalse(out.endswith("\n\n"))

    def test_sorted_keys_tight_separators(self):
        self.assertEqual(pathscan.canonical_json({"b": 1, "a": 2}), '{"a":2,"b":1}\n')

    def test_ascii_only(self):
        out = pathscan.canonical_json({"p": "caf\u00e9"})
        self.assertIn("\\u00e9", out)
        self.assertTrue(all(ord(c) < 128 for c in out))

    def test_newline_in_value_is_escaped_not_literal(self):
        out = pathscan.canonical_json({"p": "a\nb"})
        self.assertIn("\\n", out)
        self.assertEqual(out.count("\n"), 1)

    def test_deterministic(self):
        obj = {"z": [3, 1, 2], "a": {"y": 1, "x": 2}}
        self.assertEqual(pathscan.canonical_json(obj), pathscan.canonical_json(obj))


# ---------------------------------------------------------------------------
# NUL-delimited input
# ---------------------------------------------------------------------------

class TestDecodeNulList(unittest.TestCase):
    def test_empty_bytes_is_empty_list(self):
        self.assertEqual(pathscan.decode_nul_list(b"", "x"), [])

    def test_trailing_nul_is_not_an_entry(self):
        self.assertEqual(pathscan.decode_nul_list(b"a\0b\0", "x"), ["a", "b"])

    def test_missing_trailing_nul_still_parses(self):
        self.assertEqual(pathscan.decode_nul_list(b"a\0b", "x"), ["a", "b"])

    def test_single_entry(self):
        self.assertEqual(pathscan.decode_nul_list(b"only.txt\0", "x"), ["only.txt"])

    def test_newline_inside_an_entry_is_preserved(self):
        self.assertEqual(pathscan.decode_nul_list(b"a\nb.txt\0", "x"), ["a\nb.txt"])

    def test_interior_empty_entry_is_setup_error(self):
        with self.assertRaises(pathscan.SetupError):
            pathscan.decode_nul_list(b"a\0\0b\0", "x")

    def test_invalid_utf8_is_setup_error(self):
        with self.assertRaises(pathscan.SetupError):
            pathscan.decode_nul_list(b"ok\0\xff\xfe\0", "x")

    def test_error_message_names_the_source_and_index(self):
        with self.assertRaises(pathscan.SetupError) as ctx:
            pathscan.decode_nul_list(b"a\0\0b\0", "mylist")
        self.assertIn("mylist", str(ctx.exception))
        self.assertIn("entry 1", str(ctx.exception))


class TestReadPathsFrom(TempMixin, unittest.TestCase):
    def test_missing_file_is_setup_error(self):
        with self.assertRaises(pathscan.SetupError):
            pathscan.read_paths_from(os.path.join(self.tmp(), "nope"))

    def test_reads_a_written_list(self):
        p = write_list(self.tmp(), "l", ["a.txt", "b/c.txt"])
        self.assertEqual(pathscan.read_paths_from(p), ["a.txt", "b/c.txt"])

    def test_empty_file_is_zero_paths(self):
        p = write_list(self.tmp(), "l", [])
        self.assertEqual(pathscan.read_paths_from(p), [])


# ---------------------------------------------------------------------------
# Individual rules
# ---------------------------------------------------------------------------

class TestCaseFoldCollision(unittest.TestCase):
    def test_file_name_case_collision(self):
        self.assertIn(pathscan.R_CASE, rules_fired(["a/B.txt", "a/b.txt"]))

    def test_directory_component_case_collision(self):
        self.assertIn(pathscan.R_CASE, rules_fired(["A/x.txt", "a/x.txt"]))

    def test_distinct_names_do_not_collide(self):
        self.assertNotIn(pathscan.R_CASE, rules_fired(["a.txt", "b.txt"]))

    def test_members_are_sorted_and_complete(self):
        f = [x for x in scan_paths(["b.TXT", "B.txt", "b.txt"])["findings"]
             if x["rule_id"] == pathscan.R_CASE]
        self.assertEqual(len(f), 1)
        self.assertEqual(f[0]["paths"], ["B.txt", "b.TXT", "b.txt"])

    def test_pure_normalisation_pair_is_not_reported_as_case(self):
        # One defect, one rule: NFC vs NFD of the same name is a
        # normalisation collision, not a case collision.
        fired = rules_fired(["caf\u00e9.txt", "cafe\u0301.txt"])
        self.assertIn(pathscan.R_NORM, fired)
        self.assertNotIn(pathscan.R_CASE, fired)

    def test_case_and_normalisation_together_reported_as_case(self):
        fired = rules_fired(["CAF\u00c9.txt", "cafe\u0301.txt"])
        self.assertIn(pathscan.R_CASE, fired)

    def test_turkish_dotless_i_folds_together(self):
        # casefold() maps both to "i"-ish forms; documenting real behaviour.
        report = scan_paths(["I.txt", "i.txt"])
        self.assertEqual(report["summary"][pathscan.R_CASE], 1)


class TestUnicodeNormalizationCollision(unittest.TestCase):
    def test_nfc_vs_nfd(self):
        self.assertIn(pathscan.R_NORM, rules_fired(["caf\u00e9.txt", "cafe\u0301.txt"]))

    def test_identical_forms_do_not_collide(self):
        self.assertNotIn(pathscan.R_NORM, rules_fired(["caf\u00e9.txt", "other.txt"]))

    def test_detail_records_the_nfc_form(self):
        f = [x for x in scan_paths(["caf\u00e9.txt", "cafe\u0301.txt"])["findings"]
             if x["rule_id"] == pathscan.R_NORM][0]
        self.assertEqual(f["detail"]["nfc"], "caf\u00e9.txt")

    def test_ascii_only_repo_has_no_normalisation_findings(self):
        self.assertEqual(scan_paths(["a.txt", "b/c.md"])["summary"][pathscan.R_NORM], 0)


class TestWindowsReservedName(unittest.TestCase):
    def test_bare_device_name(self):
        self.assertIn(pathscan.R_RESERVED, rules_fired(["aux"]))

    def test_device_name_with_extension(self):
        self.assertIn(pathscan.R_RESERVED, rules_fired(["NUL.json"]))

    def test_device_name_in_a_directory_component(self):
        f = [x for x in scan_paths(["con/data.txt"])["findings"]
             if x["rule_id"] == pathscan.R_RESERVED][0]
        self.assertEqual(f["detail"]["components"], ["con"])

    def test_case_insensitive(self):
        for name in ("CoM1.txt", "com1.txt", "COM1"):
            self.assertIn(pathscan.R_RESERVED, rules_fired([name]), name)

    def test_com0_and_lpt0_are_not_reserved(self):
        self.assertNotIn(pathscan.R_RESERVED, rules_fired(["com0.txt", "lpt0.txt"]))

    def test_longer_name_starting_with_a_device_is_not_reserved(self):
        self.assertNotIn(pathscan.R_RESERVED, rules_fired(["console.txt", "auxiliary.md"]))


class TestTrailingDotOrSpace(unittest.TestCase):
    def test_trailing_dot(self):
        self.assertIn(pathscan.R_TRAILING, rules_fired(["summary."]))

    def test_trailing_space(self):
        self.assertIn(pathscan.R_TRAILING, rules_fired(["summary "]))

    def test_trailing_space_on_a_directory_component(self):
        f = [x for x in scan_paths(["draft /notes.md"])["findings"]
             if x["rule_id"] == pathscan.R_TRAILING][0]
        self.assertEqual(f["detail"]["components"], ["draft "])

    def test_interior_space_is_fine(self):
        self.assertNotIn(pathscan.R_TRAILING, rules_fired(["my report.md"]))

    def test_dot_and_dotdot_are_not_double_reported(self):
        # "." and ".." end with a dot but are already UNSAFE_RELATIVE_PATH.
        fired = rules_fired(["../x.txt", "./y.txt"])
        self.assertIn(pathscan.R_UNSAFE, fired)
        self.assertNotIn(pathscan.R_TRAILING, fired)


class TestControlCharacter(unittest.TestCase):
    def test_newline(self):
        f = [x for x in scan_paths(["two\nlines.txt"])["findings"]
             if x["rule_id"] == pathscan.R_CONTROL][0]
        self.assertEqual(f["detail"]["code_points"], ["U+000A"])

    def test_tab(self):
        self.assertIn(pathscan.R_CONTROL, rules_fired(["tab\there.txt"]))

    def test_del(self):
        self.assertIn(pathscan.R_CONTROL, rules_fired(["del\x7f.txt"]))

    def test_plain_name_is_clean(self):
        self.assertNotIn(pathscan.R_CONTROL, rules_fired(["plain.txt"]))

    def test_code_points_are_sorted_and_deduplicated(self):
        f = [x for x in scan_paths(["a\tb\nc\td.txt"])["findings"]
             if x["rule_id"] == pathscan.R_CONTROL][0]
        self.assertEqual(f["detail"]["code_points"], ["U+0009", "U+000A"])


class TestWindowsIllegalCharacter(unittest.TestCase):
    def test_colon(self):
        self.assertIn(pathscan.R_ILLEGAL, rules_fired(["report:v2.json"]))

    def test_question_mark_and_star(self):
        f = [x for x in scan_paths(["what?*.md"])["findings"]
             if x["rule_id"] == pathscan.R_ILLEGAL][0]
        self.assertEqual(f["detail"]["characters"], ["*", "?"])

    def test_drive_letter_colon_is_not_double_reported_as_illegal(self):
        report = scan_paths(["C:/drive/path.txt"])
        illegal = [x for x in report["findings"] if x["rule_id"] == pathscan.R_ILLEGAL]
        self.assertEqual(illegal, [])
        self.assertEqual(report["summary"][pathscan.R_UNSAFE], 1)

    def test_forward_slash_is_a_separator_not_an_illegal_character(self):
        self.assertNotIn(pathscan.R_ILLEGAL, rules_fired(["a/b/c.txt"]))


class TestUnsafeRelativePath(unittest.TestCase):
    def test_dotdot(self):
        f = [x for x in scan_paths(["../escape.txt"])["findings"]
             if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("'..' component", f["detail"]["reasons"])

    def test_absolute(self):
        f = [x for x in scan_paths(["/etc/passwd"])["findings"]
             if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("absolute path", f["detail"]["reasons"])

    def test_drive_letter(self):
        f = [x for x in scan_paths(["D:/x.txt"])["findings"]
             if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("drive-letter prefix", f["detail"]["reasons"])

    def test_backslash(self):
        f = [x for x in scan_paths(["a\\b.txt"])["findings"]
             if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("backslash separator", f["detail"]["reasons"])

    def test_trailing_separator_and_double_separator(self):
        r1 = [x for x in scan_paths(["dir/"])["findings"]
              if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("trailing separator", r1["detail"]["reasons"])
        r2 = [x for x in scan_paths(["a//b.txt"])["findings"]
              if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertIn("empty path component", r2["detail"]["reasons"])

    def test_reasons_are_sorted(self):
        f = [x for x in scan_paths(["C:\\a\\..\\b.txt"])["findings"]
             if x["rule_id"] == pathscan.R_UNSAFE][0]
        self.assertEqual(f["detail"]["reasons"], sorted(f["detail"]["reasons"]))

    def test_ordinary_relative_path_is_clean(self):
        self.assertNotIn(pathscan.R_UNSAFE, rules_fired(["src/util/x.py"]))


class TestDuplicatePath(unittest.TestCase):
    def test_repeat_is_reported_with_a_count(self):
        f = [x for x in scan_paths(["a.txt", "a.txt", "a.txt"])["findings"]
             if x["rule_id"] == pathscan.R_DUPLICATE][0]
        self.assertEqual(f["detail"]["occurrences"], 3)

    def test_distinct_paths_are_not_duplicates(self):
        self.assertNotIn(pathscan.R_DUPLICATE, rules_fired(["a.txt", "b.txt"]))

    def test_duplicate_does_not_inflate_other_rules(self):
        # aux.txt twice is one reserved-name defect, not two.
        report = scan_paths(["aux.txt", "aux.txt"])
        self.assertEqual(report["summary"][pathscan.R_RESERVED], 1)
        self.assertEqual(report["summary"][pathscan.R_DUPLICATE], 1)


# ---------------------------------------------------------------------------
# Report shape and ordering
# ---------------------------------------------------------------------------

class TestReportShape(unittest.TestCase):
    def test_clean_report_status_and_counts(self):
        r = scan_paths(["a.txt", "b/c.md"])
        self.assertEqual(r["status"], "clean")
        self.assertEqual(r["paths_scanned"], 2)
        self.assertEqual(r["distinct_paths"], 2)
        self.assertEqual(r["findings"], [])

    def test_summary_covers_every_rule_even_at_zero(self):
        r = scan_paths(["a.txt"])
        self.assertEqual(set(r["summary"]), set(pathscan.ALL_RULES))

    def test_summary_matches_finding_counts(self):
        r = scan_paths(["A.txt", "a.txt", "aux", "bad?.md"])
        counted = {}
        for f in r["findings"]:
            counted[f["rule_id"]] = counted.get(f["rule_id"], 0) + 1
        for rule, n in r["summary"].items():
            self.assertEqual(n, counted.get(rule, 0), rule)

    def test_schema_version_and_tool_name(self):
        r = scan_paths([])
        self.assertEqual(r["schema_version"], pathscan.SCHEMA_VERSION)
        self.assertEqual(r["tool"], "path-collision-scanner")

    def test_findings_sorted_by_rule_then_paths(self):
        r = scan_paths(["z.txt", "Z.txt", "aux", "b?.md", "c\nd.txt"])
        keys = [(f["rule_id"], f["paths"]) for f in r["findings"]]
        self.assertEqual(keys, sorted(keys))

    def test_input_order_does_not_change_the_report(self):
        a = ["Z.txt", "z.txt", "aux", "b?.md"]
        b = ["b?.md", "aux", "z.txt", "Z.txt"]
        self.assertEqual(pathscan.canonical_json(scan_paths(a)),
                         pathscan.canonical_json(scan_paths(b)))

    def test_empty_input_is_clean(self):
        r = scan_paths([])
        self.assertEqual(r["status"], "clean")
        self.assertEqual(r["paths_scanned"], 0)


class TestRuleSelection(unittest.TestCase):
    def test_subset_disables_the_others(self):
        r = pathscan.build_report(["A.txt", "a.txt", "aux"], "path-list", {pathscan.R_RESERVED})
        self.assertEqual(r["rules_enabled"], [pathscan.R_RESERVED])
        self.assertEqual({f["rule_id"] for f in r["findings"]}, {pathscan.R_RESERVED})

    def test_unknown_rule_is_setup_error(self):
        with self.assertRaises(pathscan.SetupError):
            pathscan.resolve_rules("NOT_A_RULE")

    def test_empty_rule_spec_is_setup_error(self):
        with self.assertRaises(pathscan.SetupError):
            pathscan.resolve_rules(" , ")

    def test_default_is_every_rule(self):
        self.assertEqual(pathscan.resolve_rules(None), set(pathscan.ALL_RULES))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

class TestCli(TempMixin, unittest.TestCase):
    def test_clean_fixture_exits_zero(self):
        code, out, err = run_cli(["--paths-from", "fixtures/clean.paths"], cwd=HERE)
        self.assertEqual(code, 0, msg=err + out)
        self.assertEqual(json.loads(out)["status"], "clean")

    def test_dirty_fixture_exits_one(self):
        code, out, err = run_cli(["--paths-from", "fixtures/dirty.paths"], cwd=HERE)
        self.assertEqual(code, 1, msg=err + out)
        self.assertEqual(json.loads(out)["status"], "findings")

    def test_dirty_fixture_fires_every_rule_except_duplicate(self):
        _, out, _ = run_cli(["--paths-from", "fixtures/dirty.paths"], cwd=HERE)
        fired = {f["rule_id"] for f in json.loads(out)["findings"]}
        self.assertEqual(fired, set(pathscan.ALL_RULES) - {pathscan.R_DUPLICATE})

    def test_duplicates_fixture_fires_duplicate(self):
        _, out, _ = run_cli(["--paths-from", "fixtures/duplicates.paths"], cwd=HERE)
        self.assertGreater(json.loads(out)["summary"][pathscan.R_DUPLICATE], 0)

    def test_empty_fixture_exits_zero(self):
        code, out, _ = run_cli(["--paths-from", "fixtures/empty.paths"], cwd=HERE)
        self.assertEqual(code, 0)
        self.assertEqual(json.loads(out)["paths_scanned"], 0)

    def test_malformed_fixture_exits_two(self):
        code, out, _ = run_cli(["--paths-from", "fixtures/malformed.paths"], cwd=HERE)
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_not_utf8_fixture_exits_two(self):
        code, out, _ = run_cli(["--paths-from", "fixtures/not_utf8.paths"], cwd=HERE)
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_missing_path_list_exits_two(self):
        code, out, _ = run_cli(["--paths-from", "/nonexistent.paths"])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_unknown_rule_exits_two(self):
        code, out, _ = run_cli(["--paths-from", "fixtures/clean.paths", "--rules", "NOPE"],
                               cwd=HERE)
        self.assertEqual(code, 2)

    def test_unwritable_output_exits_two(self):
        # The error report cannot go to the file that could not be opened,
        # so it falls back to stderr and stdout stays empty.
        code, out, err = run_cli(
            ["--paths-from", "fixtures/clean.paths", "-o", "/no/such/dir/r.json"], cwd=HERE)
        self.assertEqual(code, 2)
        self.assertEqual(out, "")
        self.assertEqual(json.loads(err)["status"], "error")

    def test_stdin_mode(self):
        data = b"a.txt\0A.txt\0"
        code, out, err = run_cli(["--paths-from", "-"], stdin_bytes=data)
        self.assertEqual(code, 1, msg=err)
        self.assertEqual(json.loads(out)["summary"][pathscan.R_CASE], 1)

    def test_list_rules_exits_zero_and_prints_all(self):
        code, out, _ = run_cli(["--list-rules"])
        self.assertEqual(code, 0)
        self.assertEqual(out.split(), sorted(pathscan.ALL_RULES))

    def test_output_flag_writes_file_and_silences_stdout(self):
        out_path = os.path.join(self.tmp(), "r.json")
        code, out, _ = run_cli(
            ["--paths-from", "fixtures/clean.paths", "-o", out_path], cwd=HERE)
        self.assertEqual(code, 0)
        self.assertEqual(out.strip(), "")
        with open(out_path, "rb") as fh:
            data = fh.read()
        self.assertTrue(data.endswith(b"\n"))
        self.assertFalse(data.endswith(b"\n\n"))

    def test_repeat_runs_are_byte_identical(self):
        td = self.tmp()
        a, b = os.path.join(td, "a.json"), os.path.join(td, "b.json")
        run_cli(["--paths-from", "fixtures/dirty.paths", "-o", a], cwd=HERE)
        run_cli(["--paths-from", "fixtures/dirty.paths", "-o", b], cwd=HERE)
        with open(a, "rb") as f1, open(b, "rb") as f2:
            self.assertEqual(f1.read(), f2.read())

    def test_report_contains_no_absolute_paths_the_tool_derived(self):
        out_path = os.path.join(self.tmp(), "r.json")
        run_cli(["--paths-from", "fixtures/dirty.paths", "-o", out_path], cwd=HERE)
        with open(out_path, encoding="utf-8") as fh:
            text = fh.read()
        self.assertNotIn(HERE, text)
        self.assertNotIn("/tmp", text)
        self.assertNotIn("/home", text)


class TestRelocation(TempMixin, unittest.TestCase):
    """Two runs from the same directory prove nothing about path leakage --
    the leak would be identical in both. Copy the tool and its fixture to a
    differently *named* absolute path and hash the report again."""

    def _copy_tree(self, dest):
        os.makedirs(dest)
        shutil.copy2(PATHSCAN_PY, dest)
        shutil.copy2(MAKE_FIXTURES_PY, dest)
        shutil.copytree(FIXTURES_DIR, os.path.join(dest, "fixtures"))
        return dest

    def test_identical_report_from_two_differently_named_paths(self):
        base = self.tmp()
        one = self._copy_tree(os.path.join(base, "alpha_checkout"))
        two = self._copy_tree(os.path.join(base, "a_very_differently_named_dir"))
        digests = []
        for root in (one, two):
            out_path = os.path.join(root, "r.json")
            proc = subprocess.run(
                [PY, os.path.join(root, "pathscan.py"),
                 "--paths-from", os.path.join(root, "fixtures", "dirty.paths"),
                 "-o", out_path],
                cwd=root, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120)
            self.assertEqual(proc.returncode, 1, msg=proc.stderr.decode())
            with open(out_path, "rb") as fh:
                digests.append(hashlib.sha256(fh.read()).hexdigest())
        self.assertEqual(digests[0], digests[1])

    def test_relative_and_absolute_paths_from_give_same_report(self):
        code_a, out_a, _ = run_cli(["--paths-from", "fixtures/dirty.paths"], cwd=HERE)
        code_b, out_b, _ = run_cli(
            ["--paths-from", os.path.join(FIXTURES_DIR, "dirty.paths")], cwd="/")
        self.assertEqual(code_a, code_b)
        self.assertEqual(out_a, out_b)


@NEEDS_GIT
class TestGitMode(TempMixin, unittest.TestCase):
    def make_repo(self, names):
        root = os.path.join(self.tmp(), "repo")
        os.makedirs(root)
        env = dict(os.environ, GIT_CONFIG_GLOBAL="/dev/null", GIT_CONFIG_SYSTEM="/dev/null")
        subprocess.run(["git", "init", "-q"], cwd=root, check=True, env=env)
        for name in names:
            full = os.path.join(root, name)
            os.makedirs(os.path.dirname(full), exist_ok=True) if os.path.dirname(name) else None
            with open(full, "w", encoding="utf-8") as fh:
                fh.write("x\n")
        subprocess.run(["git", "add", "-A"], cwd=root, check=True, env=env)
        return root

    def test_git_mode_lists_tracked_paths(self):
        root = self.make_repo(["a.txt", "sub/b.txt"])
        code, out, err = run_cli(["--root", root])
        self.assertEqual(code, 0, msg=err + out)
        report = json.loads(out)
        self.assertEqual(report["source"], "git")
        self.assertEqual(report["paths_scanned"], 2)

    def test_git_mode_finds_a_planted_collision(self):
        # Two names differing only by case can coexist on Linux, which is
        # exactly why they get committed and then break elsewhere.
        root = self.make_repo(["Notes.md", "notes.md"])
        code, out, err = run_cli(["--root", root])
        self.assertEqual(code, 1, msg=err + out)
        self.assertEqual(json.loads(out)["summary"][pathscan.R_CASE], 1)

    def test_non_directory_root_is_setup_error(self):
        code, out, _ = run_cli(["--root", os.path.join(self.tmp(), "nope")])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_root_that_is_not_a_repo_is_setup_error(self):
        empty = os.path.join(self.tmp(), "plain")
        os.makedirs(empty)
        code, out, _ = run_cli(["--root", empty])
        self.assertEqual(code, 2)
        self.assertEqual(json.loads(out)["status"], "error")

    def test_git_report_contains_no_absolute_root_path(self):
        root = self.make_repo(["a.txt", "sub/b.txt"])
        _, out, _ = run_cli(["--root", root])
        self.assertNotIn(root, out)


# ---------------------------------------------------------------------------
# Fixtures and imports
# ---------------------------------------------------------------------------

class TestFixtureGenerator(unittest.TestCase):
    def test_on_disk_fixtures_match_the_generator(self):
        proc = subprocess.run([PY, MAKE_FIXTURES_PY, "--check"], cwd=HERE,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=120)
        self.assertEqual(proc.returncode, 0,
                         msg=proc.stdout.decode() + proc.stderr.decode())

    def test_generator_is_deterministic(self):
        with tempfile.TemporaryDirectory() as td:
            a, b = os.path.join(td, "a"), os.path.join(td, "b")
            make_fixtures.build(a)
            make_fixtures.build(b)
            self.assertEqual(make_fixtures.snapshot(a), make_fixtures.snapshot(b))

    def test_empty_list_encodes_to_zero_bytes(self):
        self.assertEqual(make_fixtures.encode([]), b"")

    def test_encode_round_trips_through_the_decoder(self):
        paths = ["a.txt", "b/c\nd.txt", "caf\u00e9.md"]
        self.assertEqual(pathscan.decode_nul_list(make_fixtures.encode(paths), "x"), paths)


class TestStdlibOnlyImports(unittest.TestCase):
    ALLOWED = {"argparse", "json", "os", "re", "subprocess", "sys", "unicodedata"}

    def test_pathscan_imports_only_the_allow_list(self):
        import ast
        with open(PATHSCAN_PY, encoding="utf-8") as fh:
            tree = ast.parse(fh.read())
        found = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                found.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                found.add(node.module.split(".")[0])
        self.assertEqual(found - self.ALLOWED, set(), "unexpected imports: %s" % (found - self.ALLOWED))


if __name__ == "__main__":
    unittest.main()
